project:
  type: website

website:
  title: "isss626-aug2526"
  navbar:
    right: 
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
    left:
      - text: Hands-on Exercise
        menu: 
          - href: Hands-on_Ex/Hands-on_ex01/handson_ex1.html
            text: Hands-on Exercise 1 Part 1
          - href: Hands-on_Ex/Hands-on_ex01/handson_ex1_2.html
            text: Hands-on Exercise 1 Part 2
          - href: Hands-on_Ex/Hands-on_ex02/handson_ex2_1.html
            text: Hands-on Exercise 2
          - href: Hands-on_Ex/Hands-on_ex03/handson_ex3.html
            text: Hands-on Exercise 3
          - href: Hands-on_Ex/Hands-on_ex04/handson_ex4.html
            text: Hands-on Exercise 4
          - href: Hands-on_Ex/Hands-on_ex05/handson_ex5a.html
            text: Hands-on Exercise 5a
          - href: Hands-on_Ex/Hands-on_ex05/handson_ex5b.html
            text: Hands-on Exercise 5b
          - href: Hands-on_Ex/Hands-on_ex06/handson_ex6.html
            text: Hands-on Exercise 6
          - href: Hands-on_Ex/Hands-on_ex07/handson_ex7.html
            text: Hands-on Exercise 7
          - href: Hands-on_Ex/Hands-on_ex08/handson_ex8.html
            text: Hands-on Exercise 8
          - href: Hands-on_Ex/Hands-on_ex09/handson_ex9.html
            text: Hands-on Exercise 9
      - text: In-class Exercise
        menu: 
          - href: In-class_Ex/In-class_Ex03/In-class_Ex03a.html
            text: In-class Exercise 3a
          - href: In-class_Ex/In-class_Ex03/In-class_Ex03b.html
            text: In-class Exercise 3b
          - href: In-class_Ex/In-class_Ex04/inclass_ex4.html
            text: In-class Exercise 4
          - href: In-class_Ex/In-class_Ex05/inclass_ex5.html
            text: In-class Exercise 5
          - href: In-class_Ex/In-class_Ex06/inclass_ex6.html
            text: In-class Exercise 6
          - href: In-class_Ex/In-class_Ex07/inclass_ex7.html
            text: In-class Exercise 7
          - href: In-class_Ex/In-class_Ex08/inclass_ex8.html
            text: In-class Exercise 8
          - href: In-class_Ex/In-class_Ex09/inclass_ex9.html
            text: In-class Exercise 9
          - href: In-class_Ex/In-class_Ex10/inclass_ex10.html
            text: In-class Exercise 10
      - text: Take-home Exercise
        menu: 
          - href: Take-home_Ex/Take-home_Ex1/takehome_ex1.html
            text: Take-home Exercise 1
          - href: Take-home_Ex/Take-home_Ex2/takehome_ex2.html
            text: Take-home Exercise 2
          - href: Take-home_Ex/Take-home_Ex3/takehome_ex3.html
            text: Take-home Exercise 3
          
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

