project:
  type: website

website:
  title: "isss626-aug2526"
  navbar:
    right: 
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
    left:
      - text: Hands-on Exercise
        menu: 
          - href: Hands-on_Ex/Hands-on_ex01/handson_ex1.html
            text: Hands-on Exercise 1 Part 1
          - href: Hands-on_Ex/Hands-on_ex01/handson_ex1_2.html
            text: Hands-on Exercise 1 Part 2
          - href: Hands-on_Ex/Hands-on_ex02/handson_ex2_1.html
            text: Hands-on Exercise 2
          - href: Hands-on_Ex/Hands-on_ex03/handson_ex3.html
            text: Hands-on Exercise 3
          - href: Hands-on_Ex/Hands-on_ex04/handson_ex4.html
            text: Hands-on Exercise 4
      - text: In-class Exercise
        menu: 
          - href: In-class_Ex/In-class_Ex03/In-class_Ex03a.html
            text: In-class Exercise 3a
          - href: In-class_Ex/In-class_Ex03/In-class_Ex03b.html
            text: In-class Exercise 3b
      - text: Take-home Exercise
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

