---
title: "In-class Exercise 5: Global & Local Measures of Spatial Autocorrelation: sfdep methods"
author: "PHAM Hung Son"
date: "Sep 27, 2025"
date-modified: "last-modified"
format: 
  html:
    toc-depth: 4
    toc-expand: true
execute: 
  eval: true
  echo: true
  warning: false
  freeze: true
---

## **Getting the Data Into R Environment**

```{r}
pacman::p_load(sf, sfdep, tmap, tidyverse)
```

```{r}
hunan <- st_read(dsn = "data/geospatial", 
                 layer = "Hunan") 
```

```{r}
hunan2012 <- read_csv("data/aspatial/Hunan_2012.csv")
```

```{r}
hunan_GDPPC <- left_join(hunan,hunan2012) %>%
  select(1:4, 7, 15)
```

```{r}
wm_q <- hunan_GDPPC %>%
  mutate(nb = st_contiguity(geometry),
         wt = st_weights(nb, style = "W"),
         .before = 1)
```

```{r}
global_moran_perm(wm_q$GDPPC,
                        wm_q$nb,
                        wm_q$wt,
                  nsim = 99)
```

```{r}
set.seed(1234)
```

```{r}
lisa <- wm_q %>% 
  mutate(local_moran = local_moran(
    GDPPC, nb, wt, nsim = 99),
         .before = 1) %>%
  unnest(local_moran)
```

```{r}
glimpse(lisa)
```

## **5 References**

-   Kam, T. S. (2024). *Local Measures of Spatial Autocorrelation*. <https://r4gdsa.netlify.app/chap10.html>
