<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.33">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Pham Hung Son">
<meta name="dcterms.date" content="2025-09-14">

<title>Take-home Exercise 1: Geospatial Analytics for Public Good – isss626-aug2526</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-ea385d0e468b0dd5ea5bf0780b1290d9.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-dfb324f25d9b1687192fa8be62ac8f9c.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">isss626-aug2526</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-hands-on-exercise" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Hands-on Exercise</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-hands-on-exercise">    
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_ex01/handson_ex1.html">
 <span class="dropdown-text">Hands-on Exercise 1 Part 1</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_ex01/handson_ex1_2.html">
 <span class="dropdown-text">Hands-on Exercise 1 Part 2</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_ex02/handson_ex2_1.html">
 <span class="dropdown-text">Hands-on Exercise 2</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_ex03/handson_ex3.html">
 <span class="dropdown-text">Hands-on Exercise 3</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_ex04/handson_ex4.html">
 <span class="dropdown-text">Hands-on Exercise 4</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_ex05/handson_ex5a.html">
 <span class="dropdown-text">Hands-on Exercise 5a</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_ex05/handson_ex5b.html">
 <span class="dropdown-text">Hands-on Exercise 5b</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_ex06/handson_ex6.html">
 <span class="dropdown-text">Hands-on Exercise 6</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_ex07/handson_ex7.html">
 <span class="dropdown-text">Hands-on Exercise 7</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_ex08/handson_ex8.html">
 <span class="dropdown-text">Hands-on Exercise 8</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_ex09/handson_ex9.html">
 <span class="dropdown-text">Hands-on Exercise 9</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-in-class-exercise" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">In-class Exercise</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-in-class-exercise">    
        <li>
    <a class="dropdown-item" href="../../In-class_Ex/In-class_Ex03/In-class_Ex03a.html">
 <span class="dropdown-text">In-class Exercise 3a</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../In-class_Ex/In-class_Ex03/In-class_Ex03b.html">
 <span class="dropdown-text">In-class Exercise 3b</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../In-class_Ex/In-class_Ex04/inclass_ex4.html">
 <span class="dropdown-text">In-class Exercise 4</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../In-class_Ex/In-class_Ex05/inclass_ex5.html">
 <span class="dropdown-text">In-class Exercise 5</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../In-class_Ex/In-class_Ex06/inclass_ex6.html">
 <span class="dropdown-text">In-class Exercise 6</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../In-class_Ex/In-class_Ex07/inclass_ex7.html">
 <span class="dropdown-text">In-class Exercise 7</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../In-class_Ex/In-class_Ex08/inclass_ex8.html">
 <span class="dropdown-text">In-class Exercise 8</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../In-class_Ex/In-class_Ex09/inclass_ex9.html">
 <span class="dropdown-text">In-class Exercise 9</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-take-home-exercise" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Take-home Exercise</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-take-home-exercise">    
        <li>
    <a class="dropdown-item" href="../../Take-home_Ex/Take-home_Ex1/takehome_ex1.html">
 <span class="dropdown-text">Take-home Exercise 1</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Take-home_Ex/Take-home_Ex2/takehome_ex2.html">
 <span class="dropdown-text">Take-home Exercise 2</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Take-home_Ex/Take-home_Ex3/takehome_ex3.html">
 <span class="dropdown-text">Take-home Exercise 3</span></a>
  </li>  
    </ul>
  </li>
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../about.html"> 
<span class="menu-text">About</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#overview" id="toc-overview" class="nav-link active" data-scroll-target="#overview"><strong>1 Overview</strong></a></li>
  <li><a href="#getting-started" id="toc-getting-started" class="nav-link" data-scroll-target="#getting-started"><strong>2 Getting Started</strong></a>
  <ul class="collapse">
  <li><a href="#the-packages" id="toc-the-packages" class="nav-link" data-scroll-target="#the-packages"><strong>2.1 The Packages</strong></a></li>
  <li><a href="#the-data" id="toc-the-data" class="nav-link" data-scroll-target="#the-data"><strong>2.2 The Data</strong></a>
  <ul class="collapse">
  <li><a href="#business-categories-overview" id="toc-business-categories-overview" class="nav-link" data-scroll-target="#business-categories-overview"><strong>2.2.1 Business Categories Overview</strong></a></li>
  <li><a href="#datasets" id="toc-datasets" class="nav-link" data-scroll-target="#datasets"><strong>2.2.2 Datasets</strong></a></li>
  </ul></li>
  <li><a href="#data-importing-wrangling" id="toc-data-importing-wrangling" class="nav-link" data-scroll-target="#data-importing-wrangling"><strong>2.3 Data Importing &amp; Wrangling</strong></a>
  <ul class="collapse">
  <li><a href="#importing-acra-data" id="toc-importing-acra-data" class="nav-link" data-scroll-target="#importing-acra-data"><strong>2.3.1 Importing ACRA data</strong></a></li>
  <li><a href="#tidying-acra-data" id="toc-tidying-acra-data" class="nav-link" data-scroll-target="#tidying-acra-data"><strong>2.3.2 Tidying ACRA data</strong></a></li>
  <li><a href="#geocoding" id="toc-geocoding" class="nav-link" data-scroll-target="#geocoding"><strong>2.3.3 Geocoding</strong></a></li>
  </ul></li>
  </ul></li>
  <li><a href="#exploratory-observation" id="toc-exploratory-observation" class="nav-link" data-scroll-target="#exploratory-observation"><strong>3 Exploratory Observation</strong></a></li>
  <li><a href="#first-order-spatial-and-spatio-temporal-patterns-analysis" id="toc-first-order-spatial-and-spatio-temporal-patterns-analysis" class="nav-link" data-scroll-target="#first-order-spatial-and-spatio-temporal-patterns-analysis"><strong>4 First-order Spatial and Spatio-Temporal Patterns Analysis</strong></a>
  <ul class="collapse">
  <li><a href="#computing-kernel-density-estimation-kde" id="toc-computing-kernel-density-estimation-kde" class="nav-link" data-scroll-target="#computing-kernel-density-estimation-kde"><strong>4.1 Computing kernel density estimation (KDE)</strong></a></li>
  <li><a href="#spatio-temporal-kde-mapping" id="toc-spatio-temporal-kde-mapping" class="nav-link" data-scroll-target="#spatio-temporal-kde-mapping"><strong>4.2 Spatio-Temporal KDE Mapping</strong></a></li>
  <li><a href="#quadrat-counts-chi-squared-test-of-csr-using-quadrat-counts" id="toc-quadrat-counts-chi-squared-test-of-csr-using-quadrat-counts" class="nav-link" data-scroll-target="#quadrat-counts-chi-squared-test-of-csr-using-quadrat-counts"><strong>4.3 Quadrat counts &amp; Chi-squared test of CSR using quadrat counts</strong></a></li>
  </ul></li>
  <li><a href="#second-order-spatial-and-spatio-temporal-patterns-analysis" id="toc-second-order-spatial-and-spatio-temporal-patterns-analysis" class="nav-link" data-scroll-target="#second-order-spatial-and-spatio-temporal-patterns-analysis"><strong>5 Second-order Spatial and Spatio-Temporal Patterns Analysis</strong></a>
  <ul class="collapse">
  <li><a href="#clark-evan-test-for-nearest-neighbour-analysis" id="toc-clark-evan-test-for-nearest-neighbour-analysis" class="nav-link" data-scroll-target="#clark-evan-test-for-nearest-neighbour-analysis"><strong>5.1 Clark-Evan Test for Nearest Neighbour Analysis</strong></a></li>
  <li><a href="#spatial-point-patterns-analysis-methods" id="toc-spatial-point-patterns-analysis-methods" class="nav-link" data-scroll-target="#spatial-point-patterns-analysis-methods"><strong>5.2 Spatial Point Patterns Analysis Methods</strong></a></li>
  <li><a href="#spatio-temporal-point-patterns-analysis-methods" id="toc-spatio-temporal-point-patterns-analysis-methods" class="nav-link" data-scroll-target="#spatio-temporal-point-patterns-analysis-methods"><strong>5.3 Spatio-temporal Point Patterns Analysis Methods</strong></a></li>
  </ul></li>
  <li><a href="#discussion-of-results-and-implications-for-urban-planning" id="toc-discussion-of-results-and-implications-for-urban-planning" class="nav-link" data-scroll-target="#discussion-of-results-and-implications-for-urban-planning"><strong>6 Discussion of Results and Implications for Urban Planning</strong></a>
  <ul class="collapse">
  <li><a href="#results-from-analyses" id="toc-results-from-analyses" class="nav-link" data-scroll-target="#results-from-analyses"><strong>6.1 Results from Analyses</strong></a></li>
  <li><a href="#implications-for-planning-and-management" id="toc-implications-for-planning-and-management" class="nav-link" data-scroll-target="#implications-for-planning-and-management"><strong>6.2 Implications for planning and management</strong></a></li>
  </ul></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references"><strong>References</strong></a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Take-home Exercise 1: Geospatial Analytics for Public Good</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Pham Hung Son </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">September 14, 2025</p>
    </div>
  </div>
  
    <div>
    <div class="quarto-title-meta-heading">Modified</div>
    <div class="quarto-title-meta-contents">
      <p class="date-modified">November 11, 2025</p>
    </div>
  </div>
    
  </div>
  


</header>


<section id="overview" class="level1">
<h1><strong>1 Overview</strong></h1>
<p><img src="images/clipboard-2863953254.png" class="img-fluid"></p>
<p><sub><span class="smallcaps"><em>Inside&nbsp;a&nbsp;Hawker&nbsp;Center&nbsp;(via&nbsp;TripAdvisor)</em></span></sub></p>
<p>The Food &amp; Beverage (F&amp;B) sector is a vital pillar of Singapore’s economy, contributing significantly to both employment and tourism-driven revenue. In 2024, international visitor arrivals reached about <strong>16.5 million</strong>, and tourism receipts rose to <strong>S$29,781 million</strong> (or ~SGD 29.8 billion), a strong recovery to pre-pandemic levels. Among the components of tourism spend, expenditure on Food &amp; Beverage increased by 6% year-on-year in January - September 2024. The F&amp;B services sector also plays a major role domestically: for example, in July 2025, its sales reached <strong>S$1.0 billion</strong>, with fast food outlets and food caterers showing notable growth, and approximately a quarter of F&amp;B sales happening online.</p>
<p>Beyond raw numbers, the sector deeply shapes everyday life—socializing, culture, lifestyle—through restaurants, hawker centers, cafés, bars, catering, etc. The dynamic interplay between F&amp;B manufacturers, drink producers, and service-based outlets influences urban planning (where clusters of eating and dining pop up), business location decisions, land-use, and labour markets.</p>
</section>
<section id="getting-started" class="level1">
<h1><strong>2 Getting Started</strong></h1>
<section id="the-packages" class="level2">
<h2 class="anchored" data-anchor-id="the-packages"><strong>2.1 The Packages</strong></h2>
<p>In this exercise, we will use following packages:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Package</th>
<th>Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><a href="https://r-spatial.github.io/sf/"><strong>sf</strong></a></td>
<td>Provides functions to manage, processing, and manipulate <strong>Simple Features</strong>, a formal geospatial data standard that specifies a storage and access model of spatial geometries such as points, lines, and polygons.</td>
</tr>
<tr class="even">
<td><a href="https://spatstat.org/"><strong>spatstat</strong></a></td>
<td>Provides functions for spatial statistics with a strong focus on analysing spatial point patterns.</td>
</tr>
<tr class="odd">
<td><a href="https://cran.r-project.org/web/packages/stpp/index.html"><strong>stpp</strong></a></td>
<td>Provides statistical tools for analyzing the global and local second-order properties of spatio-temporal point processes.</td>
</tr>
<tr class="even">
<td><a href="https://www.tidyverse.org/"><strong>tidyverse</strong></a></td>
<td>Provides collection of functions for performing data science task such as importing, tidying, wrangling data and visualising data.</td>
</tr>
<tr class="odd">
<td><a href="https://cran.r-project.org/web/packages/tmap/"><strong>tmap</strong></a></td>
<td>Provides functions for plotting cartographic quality static point patterns maps or interactive maps by using <a href="https://leafletjs.com/">leaflet</a> API.</td>
</tr>
<tr class="even">
<td><a href="https://httr.r-lib.org/"><strong>httr</strong></a></td>
<td>Provide a wrapper for the&nbsp;<a href="https://cran.r-project.org/web/packages/curl/vignettes/intro.html"><strong>curl</strong></a>&nbsp;package, customised to the demands of modern web APIs.</td>
</tr>
<tr class="odd">
<td><a href="https://lubridate.tidyverse.org/"><strong>lubridate</strong></a></td>
<td>Provides a set of functions for working with date-times.</td>
</tr>
<tr class="even">
<td><a href="https://cran.r-project.org/web/packages/splancs/index.html"><strong>splancs</strong></a></td>
<td>For display and analysis of spatial point pattern data.</td>
</tr>
<tr class="odd">
<td><a href="https://cran.r-project.org/web/packages/sfdep/index.html"><strong>sfdep</strong></a></td>
<td>An interface to ‘spdep’ to integrate with ‘sf’ objects and the ‘tidyverse’.</td>
</tr>
<tr class="even">
<td><a href="https://cran.r-project.org/web/packages/surveillance/index.html"><strong>surveillance</strong></a></td>
<td>Statistical methods for the modeling and monitoring of time series of counts, proportions and categorical data, as well as for the modeling of continuous-time point processes of epidemic phenomena.</td>
</tr>
</tbody>
</table>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>pacman<span class="sc">::</span><span class="fu">p_load</span>(tidyverse, sf, spatstat, stpp, tmap, httr, lubridate, splancs, sfdep, surveillance)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="the-data" class="level2">
<h2 class="anchored" data-anchor-id="the-data"><strong>2.2 The Data</strong></h2>
<section id="business-categories-overview" class="level3">
<h3 class="anchored" data-anchor-id="business-categories-overview"><strong>2.2.1 Business Categories Overview</strong></h3>
<p>Using the <strong>Singapore Standard Industrial Classification (SSIC) 2020</strong>, three business categories were selected for analysis: <strong>Food and Beverage Service Activities (Division 56), Manufacture of Other Food Products (Group 107), and Manufacture of Beverages (Group 110)</strong>. Together, they span the spectrum from <strong>food production and processing</strong> to <strong>retail consumption</strong>, providing a comprehensive view of how food-related businesses emerge and evolve across the city. Examining their spatial and temporal patterns allows us to understand not only where F&amp;B establishments are located, but also how they interact with upstream manufacturers and beverage producers. This holistic perspective offers valuable insights into the clustering of economic activities, the shaping of commercial districts, and the role of the F&amp;B ecosystem in supporting urban development and community life.</p>
<p>Below is the details of the business type selected:</p>
<p><strong>56 – Food and Beverage Service Activities</strong></p>
<ul>
<li><strong>Division 56</strong>: Food and beverage service activities
<ul>
<li><p>Includes: Restaurants, cafés, fast food outlets, food courts, coffee shops, hawker centers, caterers, pubs, bars, nightclubs, and other drinking places.</p></li>
<li><p>Covers businesses primarily engaged in <strong>preparing meals, snacks, and drinks for immediate consumption</strong>.</p></li>
</ul></li>
</ul>
<p><strong>107 – Manufacture of Other Food Products</strong></p>
<ul>
<li><p><strong>Division 10</strong>: Manufacture of food products</p></li>
<li><p><strong>Group 107</strong>: Manufacture of other food products</p>
<ul>
<li><p>Includes:</p>
<ul>
<li><p><strong>1071</strong> – Manufacture of bakery products (bread, biscuits, cakes, confectionery)</p></li>
<li><p><strong>1074</strong> – Manufacture of macaroni, noodles, vermicelli and related products</p></li>
<li><p><strong>1075</strong> – Manufacture of prepared meals and dishes (e.g., frozen dinners)</p></li>
<li><p><strong>1076</strong> – Manufacture of coffee, tea and related products</p></li>
<li><p><strong>1079</strong> – Manufacture of other food products n.e.c. (sauces, soya products, spices, chips, crackers, titbits)</p></li>
</ul></li>
</ul></li>
</ul>
<p><strong>110 – Manufacture of Beverages</strong></p>
<ul>
<li><p><strong>Division 11</strong>: Manufacture of beverages</p></li>
<li><p><strong>Group 110</strong>: Manufacture of beverages</p>
<ul>
<li><p>Includes:</p>
<ul>
<li><p><strong>1101</strong> – Distilling, rectifying and blending of spirits</p></li>
<li><p><strong>1102</strong> – Manufacture of wines</p></li>
<li><p><strong>1103</strong> – Manufacture of malt liquors and malt (beer, stout)</p></li>
<li><p><strong>1104</strong> – Manufacture of soft drinks, bottled/mineral waters, cordials, syrups, composite concentrates, and ice.</p></li>
</ul></li>
</ul></li>
</ul>
</section>
<section id="datasets" class="level3">
<h3 class="anchored" data-anchor-id="datasets"><strong>2.2.2 Datasets</strong></h3>
<table class="caption-top table">
<thead>
<tr class="header">
<th><strong>Dataset Name</strong></th>
<th><strong>Description</strong></th>
<th><strong>Format</strong></th>
<th><strong>Source</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>ACRA (Accounting and Corporate Regulatory Authority) Information on Corporate Entities</td>
<td>Datasets of registered entities in Singapore. (We will select business entities registered between 1st January 2024 to 30th June 2025.)</td>
<td>CSV</td>
<td><a href="https://data.gov.sg/collections/2/view">data.gov.sg</a></td>
</tr>
<tr class="even">
<td>SSIC: Singapore Standard Industrial Classification (SSIC)</td>
<td>Official system for classifying economic activity of business establishments in Singapore.</td>
<td>XLSX</td>
<td><a href="https://classification.codes/classifications/industry/ssic-singapore">SSIC</a></td>
</tr>
<tr class="odd">
<td>Singapore Master Plan 2019 (URA) Zoning Data</td>
<td>Singapore’s land-use zones: residential, commercial, mixed-use, industrial.</td>
<td>GEOJSON</td>
<td><a href="https://data.gov.sg/datasets/d_8594ae9ff96d0c708bc2af633048edfb/view">data.gov.sg</a></td>
</tr>
</tbody>
</table>
</section>
</section>
<section id="data-importing-wrangling" class="level2">
<h2 class="anchored" data-anchor-id="data-importing-wrangling"><strong>2.3 Data Importing &amp; Wrangling</strong></h2>
<section id="importing-acra-data" class="level3">
<h3 class="anchored" data-anchor-id="importing-acra-data"><strong>2.3.1 Importing ACRA data</strong></h3>
<p>The ACRA Corporate Entities CSV files were imported into R using <a href="https://www.tidyverse.org/"><strong>tidyverse</strong></a>. The first 24 columns were retained, covering entity identifiers, names, incorporation dates, SSIC codes, and addresses. This ensured consistency across all files as we are dropping the unnecessary fields such as fields with excessive missing values or fields with only single values.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>folder_path <span class="ot">&lt;-</span> <span class="st">"data/aspatial/ACRA"</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>file_list <span class="ot">&lt;-</span> <span class="fu">list.files</span>(<span class="at">path =</span> folder_path,</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>                        <span class="at">pattern =</span> <span class="st">"^ACRA*.*</span><span class="sc">\\</span><span class="st">.csv$"</span>,</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>                        <span class="at">full.names =</span> <span class="cn">TRUE</span>)</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>acra_data <span class="ot">&lt;-</span> file_list <span class="sc">%&gt;%</span></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">map_dfr</span>(read_csv)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(acra_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 2,026,935
Columns: 53
$ uen                               &lt;chr&gt; "00022100K", "00031800X", "00043100A…
$ issuance_agency_id                &lt;chr&gt; "ACRA", "ACRA", "ACRA", "ACRA", "ACR…
$ entity_name                       &lt;chr&gt; "A Y ABDUL RAHIMAN", "A M ABDULLAH S…
$ entity_type_description           &lt;chr&gt; "Sole Proprietorship/ Partnership", …
$ business_constitution_description &lt;chr&gt; "Partnership", "Partnership", "Partn…
$ company_type_description          &lt;chr&gt; "na", "na", "na", "na", "na", "na", …
$ paf_constitution_description      &lt;chr&gt; "na", "na", "na", "na", "na", "na", …
$ entity_status_description         &lt;chr&gt; "Terminated", "Terminated", "Termina…
$ registration_incorporation_date   &lt;date&gt; 1974-10-09, 1974-10-12, 1974-09-20,…
$ uen_issue_date                    &lt;date&gt; 1974-10-09, 1974-10-12, 1974-09-20,…
$ address_type                      &lt;chr&gt; "LOCAL", "LOCAL", "LOCAL", "LOCAL", …
$ block                             &lt;chr&gt; "51", "93", "178", "21", "30", "38A"…
$ street_name                       &lt;chr&gt; "EAST COAST ROAD", "MARKET STREET", …
$ level_no                          &lt;chr&gt; "na", "10", "na", "na", "na", "na", …
$ unit_no                           &lt;chr&gt; "na", "01", "na", "na", "na", "na", …
$ building_name                     &lt;chr&gt; "na", "na", "na", "na", "na", "na", …
$ postal_code                       &lt;chr&gt; "428770", "0104", "0718", "0923", "4…
$ other_address_line1               &lt;chr&gt; "na", "na", "na", "na", "na", "na", …
$ other_address_line2               &lt;chr&gt; "na", "na", "na", "na", "na", "na", …
$ account_due_date                  &lt;chr&gt; "na", "na", "na", "na", "na", "na", …
$ annual_return_date                &lt;chr&gt; "na", "na", "na", "na", "na", "na", …
$ primary_ssic_code                 &lt;dbl&gt; 47722, 46301, 68104, 56111, 47102, 6…
$ primary_ssic_description          &lt;chr&gt; "na", "na", "na", "na", "na", "na", …
$ primary_user_described_activity   &lt;chr&gt; "na", "na", "na", "na", "na", "na", …
$ secondary_ssic_code               &lt;chr&gt; "na", "32909", "na", "56122", "na", …
$ secondary_ssic_description        &lt;chr&gt; "na", "na", "na", "na", "na", "na", …
$ secondary_user_described_activity &lt;chr&gt; "na", "na", "na", "na", "na", "na", …
$ no_of_officers                    &lt;dbl&gt; 7, 6, 3, 1, 5, 2, 2, 1, 4, 2, 2, 1, …
$ former_entity_name1               &lt;chr&gt; "na", "na", "na", "na", "na", "na", …
$ former_entity_name2               &lt;chr&gt; "na", "na", "na", "na", "na", "na", …
$ former_entity_name3               &lt;chr&gt; "na", "na", "na", "na", "na", "na", …
$ former_entity_name4               &lt;chr&gt; "na", "na", "na", "na", "na", "na", …
$ former_entity_name5               &lt;chr&gt; "na", "na", "na", "na", "na", "na", …
$ former_entity_name6               &lt;chr&gt; "na", "na", "na", "na", "na", "na", …
$ former_entity_name7               &lt;chr&gt; "na", "na", "na", "na", "na", "na", …
$ former_entity_name8               &lt;chr&gt; "na", "na", "na", "na", "na", "na", …
$ former_entity_name9               &lt;chr&gt; "na", "na", "na", "na", "na", "na", …
$ former_entity_name10              &lt;chr&gt; "na", "na", "na", "na", "na", "na", …
$ former_entity_name11              &lt;chr&gt; "na", "na", "na", "na", "na", "na", …
$ former_entity_name12              &lt;chr&gt; "na", "na", "na", "na", "na", "na", …
$ former_entity_name13              &lt;chr&gt; "na", "na", "na", "na", "na", "na", …
$ former_entity_name14              &lt;chr&gt; "na", "na", "na", "na", "na", "na", …
$ former_entity_name15              &lt;chr&gt; "na", "na", "na", "na", "na", "na", …
$ uen_of_audit_firm1                &lt;chr&gt; "na", "na", "na", "na", "na", "na", …
$ name_of_audit_firm1               &lt;chr&gt; "na", "na", "na", "na", "na", "na", …
$ uen_of_audit_firm2                &lt;chr&gt; "na", "na", "na", "na", "na", "na", …
$ name_of_audit_firm2               &lt;chr&gt; "na", "na", "na", "na", "na", "na", …
$ uen_of_audit_firm3                &lt;chr&gt; "na", "na", "na", "na", "na", "na", …
$ name_of_audit_firm3               &lt;chr&gt; "na", "na", "na", "na", "na", "na", …
$ uen_of_audit_firm4                &lt;chr&gt; "na", "na", "na", "na", "na", "na", …
$ name_of_audit_firm4               &lt;chr&gt; "na", "na", "na", "na", "na", "na", …
$ uen_of_audit_firm5                &lt;chr&gt; "na", "na", "na", "na", "na", "na", …
$ name_of_audit_firm5               &lt;chr&gt; "na", "na", "na", "na", "na", "na", …</code></pre>
</div>
</div>
<p>The dataset consists of 2,026,935 rows and 53 columns.</p>
</section>
<section id="tidying-acra-data" class="level3">
<h3 class="anchored" data-anchor-id="tidying-acra-data"><strong>2.3.2 Tidying ACRA data</strong></h3>
<p><strong>Standardisation of Key Fields</strong><br>
Column names were renamed to a common schema (<code>date</code>, <code>ssic_raw</code>, <code>postal_code</code>). Dates were converted into proper R <code>Date</code> objects. SSIC codes were cleaned to numeric strings, and <strong>2-digit</strong> (<code>ssic_2d</code>) and <strong>3-digit</strong> (<code>ssic_3d</code>) prefixes were extracted. Postal codes were also padded to six digits for consistency.</p>
<p><strong>Temporal Filtering</strong><br>
Only businesses registered between <strong>01-Jan-2024 and 30-Jun-2025</strong> were retained, aligning with the study’s spatio-temporal scope. Records with missing or invalid dates were excluded.</p>
<p><strong>Business Type Selection</strong><br>
The dataset was filtered to include only the <strong>Food and Beverage / Hospitality categories</strong>: <strong>Division 56</strong> – Food &amp; Beverage Service Activities, <strong>Group 107</strong> – Manufacture of Other Food Products, <strong>Group 110</strong> – Manufacture of Beverages</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>date_min <span class="ot">&lt;-</span> <span class="fu">as_date</span>(<span class="st">"2024-01-01"</span>)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>date_max <span class="ot">&lt;-</span> <span class="fu">as_date</span>(<span class="st">"2025-06-30"</span>)</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>acra_all_fnb <span class="ot">&lt;-</span> acra_data <span class="sc">%&gt;%</span></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>  <span class="co"># keep the first 24 cols </span></span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">24</span>) <span class="sc">%&gt;%</span></span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>  <span class="co"># commonize column names </span></span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(</span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">date        =</span> registration_incorporation_date,</span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">ssic_raw    =</span> primary_ssic_code,</span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">postal_code =</span> postal_code</span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb5-14"><a href="#cb5-14" aria-hidden="true" tabindex="-1"></a>    <span class="co"># dates</span></span>
<span id="cb5-15"><a href="#cb5-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">date =</span> <span class="fu">as_date</span>(date),</span>
<span id="cb5-16"><a href="#cb5-16" aria-hidden="true" tabindex="-1"></a>    <span class="co"># SSIC as character </span></span>
<span id="cb5-17"><a href="#cb5-17" aria-hidden="true" tabindex="-1"></a>    <span class="at">ssic_raw =</span> <span class="fu">as.character</span>(ssic_raw),</span>
<span id="cb5-18"><a href="#cb5-18" aria-hidden="true" tabindex="-1"></a>    <span class="at">ssic_raw =</span> <span class="fu">str_replace_all</span>(ssic_raw, <span class="st">"[^0-9]"</span>, <span class="st">""</span>),   </span>
<span id="cb5-19"><a href="#cb5-19" aria-hidden="true" tabindex="-1"></a>    <span class="at">ssic_2d  =</span> <span class="fu">str_sub</span>(ssic_raw, <span class="dv">1</span>, <span class="dv">2</span>),</span>
<span id="cb5-20"><a href="#cb5-20" aria-hidden="true" tabindex="-1"></a>    <span class="at">ssic_3d  =</span> <span class="fu">str_sub</span>(ssic_raw, <span class="dv">1</span>, <span class="dv">3</span>),</span>
<span id="cb5-21"><a href="#cb5-21" aria-hidden="true" tabindex="-1"></a>    <span class="co"># clean postal code to 6-digit with zeros</span></span>
<span id="cb5-22"><a href="#cb5-22" aria-hidden="true" tabindex="-1"></a>    <span class="at">postal_code =</span> <span class="fu">str_pad</span>(postal_code, <span class="at">width =</span> <span class="dv">6</span>, <span class="at">side =</span> <span class="st">"left"</span>, <span class="at">pad =</span> <span class="st">"0"</span>)</span>
<span id="cb5-23"><a href="#cb5-23" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb5-24"><a href="#cb5-24" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb5-25"><a href="#cb5-25" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(date), date <span class="sc">&gt;=</span> date_min, date <span class="sc">&lt;=</span> date_max) <span class="sc">%&gt;%</span></span>
<span id="cb5-26"><a href="#cb5-26" aria-hidden="true" tabindex="-1"></a>  <span class="co"># target Division 56 OR Group 107 OR Group 110</span></span>
<span id="cb5-27"><a href="#cb5-27" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(ssic_2d <span class="sc">==</span> <span class="st">"56"</span> <span class="sc">|</span> ssic_3d <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"107"</span>, <span class="st">"110"</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb5-28"><a href="#cb5-28" aria-hidden="true" tabindex="-1"></a>  <span class="co"># time fields</span></span>
<span id="cb5-29"><a href="#cb5-29" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb5-30"><a href="#cb5-30" aria-hidden="true" tabindex="-1"></a>  <span class="at">YEAR       =</span> lubridate<span class="sc">::</span><span class="fu">year</span>(date),</span>
<span id="cb5-31"><a href="#cb5-31" aria-hidden="true" tabindex="-1"></a>  <span class="at">MONTH_NUM  =</span> lubridate<span class="sc">::</span><span class="fu">month</span>(date),</span>
<span id="cb5-32"><a href="#cb5-32" aria-hidden="true" tabindex="-1"></a>  <span class="at">MONTH_ABBR =</span> lubridate<span class="sc">::</span><span class="fu">month</span>(date, <span class="at">label =</span> <span class="cn">TRUE</span>, <span class="at">abbr =</span> <span class="cn">TRUE</span>),</span>
<span id="cb5-33"><a href="#cb5-33" aria-hidden="true" tabindex="-1"></a>    <span class="at">fnb_bucket =</span> <span class="fu">case_when</span>(</span>
<span id="cb5-34"><a href="#cb5-34" aria-hidden="true" tabindex="-1"></a>      ssic_2d <span class="sc">==</span> <span class="st">"56"</span>          <span class="sc">~</span> <span class="st">"F&amp;B Services (Div 56)"</span>,</span>
<span id="cb5-35"><a href="#cb5-35" aria-hidden="true" tabindex="-1"></a>      ssic_3d <span class="sc">==</span> <span class="st">"107"</span>         <span class="sc">~</span> <span class="st">"Food Manufacturing (Grp 107)"</span>,</span>
<span id="cb5-36"><a href="#cb5-36" aria-hidden="true" tabindex="-1"></a>      ssic_3d <span class="sc">==</span> <span class="st">"110"</span>         <span class="sc">~</span> <span class="st">"Beverage Manufacturing (Grp 110)"</span>,</span>
<span id="cb5-37"><a href="#cb5-37" aria-hidden="true" tabindex="-1"></a>      <span class="cn">TRUE</span>                     <span class="sc">~</span> <span class="st">"Other"</span></span>
<span id="cb5-38"><a href="#cb5-38" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb5-39"><a href="#cb5-39" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p><strong>Sanity Checks &amp; Subsets</strong><br>
Basic counts by <code>fnb_bucket</code> were generated to confirm category distribution. Monthly registration summaries were produced to validate temporal coverage. Separate data frames (<code>biz_56</code>, <code>biz_107</code>, <code>biz_110</code>) were created for more detailed subgroup analysis.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Counts by bucket</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>acra_all_fnb <span class="sc">%&gt;%</span> <span class="fu">count</span>(fnb_bucket, <span class="at">sort =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 2
  fnb_bucket                           n
  &lt;chr&gt;                            &lt;int&gt;
1 F&amp;B Services (Div 56)             5758
2 Food Manufacturing (Grp 107)       737
3 Beverage Manufacturing (Grp 110)    30</code></pre>
</div>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Monthly registrations for later plotting</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>acra_all_fnb <span class="sc">%&gt;%</span></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(<span class="at">YYYYMM =</span> <span class="fu">floor_date</span>(date, <span class="st">"month"</span>), fnb_bucket) <span class="sc">%&gt;%</span></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(YYYYMM, fnb_bucket)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 52 × 3
   YYYYMM     fnb_bucket                           n
   &lt;date&gt;     &lt;chr&gt;                            &lt;int&gt;
 1 2024-01-01 Beverage Manufacturing (Grp 110)     2
 2 2024-01-01 F&amp;B Services (Div 56)              337
 3 2024-01-01 Food Manufacturing (Grp 107)        51
 4 2024-02-01 Beverage Manufacturing (Grp 110)     1
 5 2024-02-01 F&amp;B Services (Div 56)              236
 6 2024-02-01 Food Manufacturing (Grp 107)        39
 7 2024-03-01 Beverage Manufacturing (Grp 110)     1
 8 2024-03-01 F&amp;B Services (Div 56)              338
 9 2024-03-01 Food Manufacturing (Grp 107)        43
10 2024-04-01 Beverage Manufacturing (Grp 110)     1
# ℹ 42 more rows</code></pre>
</div>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># separate data frames for each bucket</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>biz_56  <span class="ot">&lt;-</span> acra_all_fnb <span class="sc">%&gt;%</span> <span class="fu">filter</span>(ssic_2d <span class="sc">==</span> <span class="st">"56"</span>)</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>biz_107 <span class="ot">&lt;-</span> acra_all_fnb <span class="sc">%&gt;%</span> <span class="fu">filter</span>(ssic_3d <span class="sc">==</span> <span class="st">"107"</span>)</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>biz_110 <span class="ot">&lt;-</span> acra_all_fnb <span class="sc">%&gt;%</span> <span class="fu">filter</span>(ssic_3d <span class="sc">==</span> <span class="st">"110"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Date column named `date` and a month column for plotting later:</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>acra_all_fnb <span class="ot">&lt;-</span> acra_all_fnb <span class="sc">%&gt;%</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">date  =</span> <span class="fu">as.Date</span>(date),</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">month =</span> <span class="fu">floor_date</span>(date, <span class="st">"month"</span>),</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">postal_code =</span> stringr<span class="sc">::</span><span class="fu">str_pad</span>(postal_code, <span class="dv">6</span>, <span class="at">pad =</span> <span class="st">"0"</span>)</span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a>biz_56  <span class="ot">&lt;-</span> biz_56  <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="at">postal_code =</span> stringr<span class="sc">::</span><span class="fu">str_pad</span>(postal_code, <span class="dv">6</span>, <span class="at">pad =</span> <span class="st">"0"</span>))</span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a>biz_107 <span class="ot">&lt;-</span> biz_107 <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="at">postal_code =</span> stringr<span class="sc">::</span><span class="fu">str_pad</span>(postal_code, <span class="dv">6</span>, <span class="at">pad =</span> <span class="st">"0"</span>))</span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a>biz_110 <span class="ot">&lt;-</span> biz_110 <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="at">postal_code =</span> stringr<span class="sc">::</span><span class="fu">str_pad</span>(postal_code, <span class="dv">6</span>, <span class="at">pad =</span> <span class="st">"0"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
</section>
<section id="geocoding" class="level3">
<h3 class="anchored" data-anchor-id="geocoding"><strong>2.3.3 Geocoding</strong></h3>
<p><strong>Extract Unique Postcodes</strong><br>
Unique six-digit postal codes were extracted from the ACRA dataset. To ensure consistency, codes were padded with leading zeros where necessary and invalid entries (missing or non-numeric) were excluded.</p>
<p><strong>Query the OneMap API</strong><br>
Each postcode was sent to the OneMap Singapore API using the code chunk below. The API returned address details and coordinates (<code>X</code>, <code>Y</code> in SVY21 projection; <code>LATITUDE</code>, <code>LONGITUDE</code> in WGS84). Postcodes with no matches were logged separately for later review.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>rds_found     <span class="ot">&lt;-</span> <span class="st">"data/rds/geocode_found.rds"</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>rds_not_found <span class="ot">&lt;-</span> <span class="st">"data/rds/geocode_not_found.rds"</span></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="fu">file.exists</span>(rds_found) <span class="sc">&amp;&amp;</span> <span class="fu">file.exists</span>(rds_not_found)) {</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>  found     <span class="ot">&lt;-</span> <span class="fu">readRDS</span>(rds_found)</span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>  not_found <span class="ot">&lt;-</span> <span class="fu">readRDS</span>(rds_not_found)</span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>} <span class="cf">else</span> {</span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a>postcodes <span class="ot">&lt;-</span> <span class="fu">unique</span>(acra_all_fnb<span class="sc">$</span>postal_code)</span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a>url <span class="ot">&lt;-</span> <span class="st">"https://onemap.gov.sg/api/common/elastic/search"</span></span>
<span id="cb12-11"><a href="#cb12-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-12"><a href="#cb12-12" aria-hidden="true" tabindex="-1"></a>found <span class="ot">&lt;-</span> <span class="fu">data.frame</span>()</span>
<span id="cb12-13"><a href="#cb12-13" aria-hidden="true" tabindex="-1"></a>not_found <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">postcode =</span> <span class="fu">character</span>())</span>
<span id="cb12-14"><a href="#cb12-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-15"><a href="#cb12-15" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (pc <span class="cf">in</span> postcodes) {</span>
<span id="cb12-16"><a href="#cb12-16" aria-hidden="true" tabindex="-1"></a>  query <span class="ot">&lt;-</span> <span class="fu">list</span>(</span>
<span id="cb12-17"><a href="#cb12-17" aria-hidden="true" tabindex="-1"></a>    <span class="at">searchVal =</span> pc,</span>
<span id="cb12-18"><a href="#cb12-18" aria-hidden="true" tabindex="-1"></a>    <span class="at">returnGeom =</span> <span class="st">"Y"</span>,</span>
<span id="cb12-19"><a href="#cb12-19" aria-hidden="true" tabindex="-1"></a>    <span class="at">getAddrDetails =</span> <span class="st">"Y"</span>,</span>
<span id="cb12-20"><a href="#cb12-20" aria-hidden="true" tabindex="-1"></a>    <span class="at">pageNum =</span> <span class="st">"1"</span></span>
<span id="cb12-21"><a href="#cb12-21" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb12-22"><a href="#cb12-22" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb12-23"><a href="#cb12-23" aria-hidden="true" tabindex="-1"></a>  res <span class="ot">&lt;-</span> <span class="fu">GET</span>(url, <span class="at">query =</span> query)</span>
<span id="cb12-24"><a href="#cb12-24" aria-hidden="true" tabindex="-1"></a>  json <span class="ot">&lt;-</span> <span class="fu">content</span>(res)</span>
<span id="cb12-25"><a href="#cb12-25" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb12-26"><a href="#cb12-26" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span>(json<span class="sc">$</span>found <span class="sc">!=</span> <span class="dv">0</span>) {</span>
<span id="cb12-27"><a href="#cb12-27" aria-hidden="true" tabindex="-1"></a>    df <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(json<span class="sc">$</span>results, <span class="at">stringsAsFactors =</span> <span class="cn">FALSE</span>)</span>
<span id="cb12-28"><a href="#cb12-28" aria-hidden="true" tabindex="-1"></a>    df<span class="sc">$</span>input_postcode <span class="ot">&lt;-</span> pc</span>
<span id="cb12-29"><a href="#cb12-29" aria-hidden="true" tabindex="-1"></a>    found <span class="ot">&lt;-</span> <span class="fu">bind_rows</span>(found, df)</span>
<span id="cb12-30"><a href="#cb12-30" aria-hidden="true" tabindex="-1"></a>  } <span class="cf">else</span> {</span>
<span id="cb12-31"><a href="#cb12-31" aria-hidden="true" tabindex="-1"></a>    not_found <span class="ot">&lt;-</span> <span class="fu">bind_rows</span>(not_found, <span class="fu">data.frame</span>(<span class="at">postcode =</span> pc))</span>
<span id="cb12-32"><a href="#cb12-32" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb12-33"><a href="#cb12-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-34"><a href="#cb12-34" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb12-35"><a href="#cb12-35" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-36"><a href="#cb12-36" aria-hidden="true" tabindex="-1"></a><span class="fu">dir.create</span>(<span class="st">"data"</span>, <span class="at">showWarnings =</span> <span class="cn">FALSE</span>)</span>
<span id="cb12-37"><a href="#cb12-37" aria-hidden="true" tabindex="-1"></a>  <span class="fu">saveRDS</span>(found, rds_found)</span>
<span id="cb12-38"><a href="#cb12-38" aria-hidden="true" tabindex="-1"></a>  <span class="fu">saveRDS</span>(not_found, rds_not_found)</span>
<span id="cb12-39"><a href="#cb12-39" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p><strong>Append Geocoding Results</strong><br>
Geocoding was performed by extracting unique six-digit postal codes from the ACRA dataset and submitting them to the OneMap Singapore API. The API returned both address details and geographic coordinates, which were then joined back to the business records. Invalid or missing coordinates were cleaned, and duplicates were removed to ensure data quality. The final datasets were converted into spatial features (<code>sf</code> objects) in the SVY21 projection (EPSG:3414), enabling integration with planning boundaries and spatial analysis. To ensure reproducibility and avoid repeated API calls, the geocoded datasets and unresolved cases were saved as <code>.rds</code> files.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>found <span class="ot">&lt;-</span> found <span class="sc">%&gt;%</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>  <span class="co">#X/Y from OneMap are SVY21 (EPSG:3414); coerce to numeric</span></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">X =</span> <span class="fu">suppressWarnings</span>(<span class="fu">as.numeric</span>(X)),</span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">Y =</span> <span class="fu">suppressWarnings</span>(<span class="fu">as.numeric</span>(Y))</span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a>  <span class="co"># keep the essential columns</span></span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>acra_all_fnb <span class="ot">&lt;-</span> acra_all_fnb <span class="sc">%&gt;%</span> <span class="fu">left_join</span>(found, <span class="at">by =</span> <span class="fu">c</span>(<span class="st">"postal_code"</span> <span class="ot">=</span> <span class="st">"POSTAL"</span>))</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>biz_56       <span class="ot">&lt;-</span> biz_56       <span class="sc">%&gt;%</span> <span class="fu">left_join</span>(found, <span class="at">by =</span> <span class="fu">c</span>(<span class="st">"postal_code"</span> <span class="ot">=</span> <span class="st">"POSTAL"</span>))</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>biz_107      <span class="ot">&lt;-</span> biz_107      <span class="sc">%&gt;%</span> <span class="fu">left_join</span>(found, <span class="at">by =</span> <span class="fu">c</span>(<span class="st">"postal_code"</span> <span class="ot">=</span> <span class="st">"POSTAL"</span>))</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>biz_110      <span class="ot">&lt;-</span> biz_110      <span class="sc">%&gt;%</span> <span class="fu">left_join</span>(found, <span class="at">by =</span> <span class="fu">c</span>(<span class="st">"postal_code"</span> <span class="ot">=</span> <span class="st">"POSTAL"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>df_to_sf <span class="ot">&lt;-</span> <span class="cf">function</span>(df, <span class="at">id_col =</span> <span class="cn">NULL</span>) {</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>  df2 <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="fu">across</span>(<span class="fu">any_of</span>(<span class="fu">c</span>(<span class="st">"X"</span>,<span class="st">"Y"</span>,<span class="st">"LONGITUDE"</span>,<span class="st">"LATITUDE"</span>)),</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>                  <span class="sc">~</span> <span class="fu">suppressWarnings</span>(<span class="fu">as.numeric</span>(.x))))</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> (<span class="fu">all</span>(<span class="fu">c</span>(<span class="st">"X"</span>,<span class="st">"Y"</span>) <span class="sc">%in%</span> <span class="fu">names</span>(df2))) {</span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>    df2 <span class="ot">&lt;-</span> df2 <span class="sc">%&gt;%</span> <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(X), <span class="sc">!</span><span class="fu">is.na</span>(Y))</span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> (<span class="sc">!</span><span class="fu">is.null</span>(id_col) <span class="sc">&amp;&amp;</span> id_col <span class="sc">%in%</span> <span class="fu">names</span>(df2)) {</span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a>      df2 <span class="ot">&lt;-</span> df2 <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(.data[[id_col]]) <span class="sc">%&gt;%</span> <span class="fu">slice</span>(<span class="dv">1</span>) <span class="sc">%&gt;%</span> <span class="fu">ungroup</span>()</span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a>    }</span>
<span id="cb15-11"><a href="#cb15-11" aria-hidden="true" tabindex="-1"></a>    <span class="fu">st_as_sf</span>(df2, <span class="at">coords =</span> <span class="fu">c</span>(<span class="st">"X"</span>,<span class="st">"Y"</span>), <span class="at">crs =</span> <span class="dv">3414</span>)   </span>
<span id="cb15-12"><a href="#cb15-12" aria-hidden="true" tabindex="-1"></a>  } <span class="cf">else</span> <span class="cf">if</span> (<span class="fu">all</span>(<span class="fu">c</span>(<span class="st">"LONGITUDE"</span>,<span class="st">"LATITUDE"</span>) <span class="sc">%in%</span> <span class="fu">names</span>(df2))) {</span>
<span id="cb15-13"><a href="#cb15-13" aria-hidden="true" tabindex="-1"></a>    df2 <span class="ot">&lt;-</span> df2 <span class="sc">%&gt;%</span> <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(LONGITUDE), <span class="sc">!</span><span class="fu">is.na</span>(LATITUDE))</span>
<span id="cb15-14"><a href="#cb15-14" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> (<span class="sc">!</span><span class="fu">is.null</span>(id_col) <span class="sc">&amp;&amp;</span> id_col <span class="sc">%in%</span> <span class="fu">names</span>(df2)) {</span>
<span id="cb15-15"><a href="#cb15-15" aria-hidden="true" tabindex="-1"></a>      df2 <span class="ot">&lt;-</span> df2 <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(.data[[id_col]]) <span class="sc">%&gt;%</span> <span class="fu">slice</span>(<span class="dv">1</span>) <span class="sc">%&gt;%</span> <span class="fu">ungroup</span>()</span>
<span id="cb15-16"><a href="#cb15-16" aria-hidden="true" tabindex="-1"></a>    }</span>
<span id="cb15-17"><a href="#cb15-17" aria-hidden="true" tabindex="-1"></a>    <span class="fu">st_as_sf</span>(df2, <span class="at">coords =</span> <span class="fu">c</span>(<span class="st">"LONGITUDE"</span>,<span class="st">"LATITUDE"</span>), <span class="at">crs =</span> <span class="dv">4326</span>)  </span>
<span id="cb15-18"><a href="#cb15-18" aria-hidden="true" tabindex="-1"></a>  } <span class="cf">else</span> {</span>
<span id="cb15-19"><a href="#cb15-19" aria-hidden="true" tabindex="-1"></a>    <span class="fu">stop</span>(<span class="st">"No coordinate columns found. Expected X/Y or LONGITUDE/LATITUDE. Present: "</span>,</span>
<span id="cb15-20"><a href="#cb15-20" aria-hidden="true" tabindex="-1"></a>         <span class="fu">paste</span>(<span class="fu">names</span>(df2), <span class="at">collapse =</span> <span class="st">", "</span>))</span>
<span id="cb15-21"><a href="#cb15-21" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb15-22"><a href="#cb15-22" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb15-23"><a href="#cb15-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-24"><a href="#cb15-24" aria-hidden="true" tabindex="-1"></a>acra_all_fnb_sf <span class="ot">&lt;-</span> <span class="fu">df_to_sf</span>(acra_all_fnb, <span class="at">id_col =</span> <span class="st">"uen"</span>)</span>
<span id="cb15-25"><a href="#cb15-25" aria-hidden="true" tabindex="-1"></a>biz_56_sf       <span class="ot">&lt;-</span> <span class="fu">df_to_sf</span>(biz_56,       <span class="at">id_col =</span> <span class="st">"uen"</span>)</span>
<span id="cb15-26"><a href="#cb15-26" aria-hidden="true" tabindex="-1"></a>biz_107_sf      <span class="ot">&lt;-</span> <span class="fu">df_to_sf</span>(biz_107,      <span class="at">id_col =</span> <span class="st">"uen"</span>)</span>
<span id="cb15-27"><a href="#cb15-27" aria-hidden="true" tabindex="-1"></a>biz_110_sf      <span class="ot">&lt;-</span> <span class="fu">df_to_sf</span>(biz_110,      <span class="at">id_col =</span> <span class="st">"uen"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>biz_missing <span class="ot">&lt;-</span> acra_all_fnb <span class="sc">%&gt;%</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">X =</span> <span class="fu">suppressWarnings</span>(<span class="fu">as.numeric</span>(X)), <span class="at">Y =</span> <span class="fu">suppressWarnings</span>(<span class="fu">as.numeric</span>(Y))) <span class="sc">%&gt;%</span></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="fu">is.na</span>(X) <span class="sc">|</span> <span class="fu">is.na</span>(Y))</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a><span class="fu">write_rds</span>(biz_missing, <span class="st">"data/rds/biz_missing_coords.rds"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
</section>
</section>
</section>
<section id="exploratory-observation" class="level1">
<h1><strong>3 Exploratory Observation</strong></h1>
<p>Before conducting the Spatial Point Pattern Analysis, we will first perform visualizing to better understand the underlying patterns and distributions in the data.</p>
<p>We will import the Singapore Master Plan 2019 (URA) Zoning Data:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>subzones <span class="ot">&lt;-</span> <span class="fu">st_read</span>(<span class="st">"data/geospatial/MasterPlan2019SubzoneBoundaryNoSeaGEOJSON.geojson"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_transform</span>(<span class="at">crs =</span> <span class="dv">3414</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Reading layer `MasterPlan2019SubzoneBoundaryNoSeaGEOJSON' from data source 
  `C:\sonphamsmu\isss626-aug2526\Take-home_Ex\Take-home_Ex1\data\geospatial\MasterPlan2019SubzoneBoundaryNoSeaGEOJSON.geojson' 
  using driver `GeoJSON'
Simple feature collection with 332 features and 2 fields
Geometry type: MULTIPOLYGON
Dimension:     XY
Bounding box:  xmin: 103.6057 ymin: 1.158699 xmax: 104.0885 ymax: 1.470775
Geodetic CRS:  WGS 84</code></pre>
</div>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>acra_all_fnb_sf <span class="ot">&lt;-</span> <span class="fu">st_join</span>(acra_all_fnb_sf, subzones)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Visualize the businesses on map:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tmap_mode</span>(<span class="st">"plot"</span>)</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="fu">tm_shape</span>(subzones) <span class="sc">+</span> <span class="fu">tm_borders</span>() <span class="sc">+</span></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a><span class="fu">tm_shape</span>(acra_all_fnb_sf) <span class="sc">+</span> <span class="fu">tm_dots</span>(<span class="at">col =</span> <span class="st">"fnb_bucket"</span>, <span class="at">size =</span> <span class="fl">0.05</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="takehome_ex1_files/figure-html/unnamed-chunk-20-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Reveal the distribution of newly registered businesses by month:</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>monthly_counts <span class="ot">&lt;-</span> acra_all_fnb <span class="sc">%&gt;%</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">date =</span> <span class="fu">as.Date</span>(date), <span class="at">month =</span> <span class="fu">floor_date</span>(date, <span class="st">"month"</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(month)</span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(monthly_counts, <span class="fu">aes</span>(<span class="at">x =</span> month, <span class="at">y =</span> n)) <span class="sc">+</span></span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_col</span>(<span class="at">fill =</span> <span class="st">"steelblue"</span>) <span class="sc">+</span></span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_date</span>(<span class="at">date_labels =</span> <span class="st">"%b-%Y"</span>, <span class="at">date_breaks =</span> <span class="st">"1 month"</span>) <span class="sc">+</span></span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Month of Registration"</span>, <span class="at">y =</span> <span class="st">"Number of Businesses"</span>,</span>
<span id="cb21-9"><a href="#cb21-9" aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">"Monthly New F&amp;B/Hospitality Registrations (Jan 2024 – Jun 2025)"</span>) <span class="sc">+</span></span>
<span id="cb21-10"><a href="#cb21-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">45</span>, <span class="at">hjust =</span> <span class="dv">1</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="takehome_ex1_files/figure-html/unnamed-chunk-21-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="Observation">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Observation
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li><strong>Monthly Trends</strong>: Registrations remained fairly steady at ~350–420 businesses per month. Noticeable declines occurred in Feb 2024 and Dec 2024, likely due to holiday or festive effects.</li>
<li><strong>Rebounds:</strong> Peaks in Aug 2024 and Mar 2025 suggest post-holiday rebounds.</li>
<li><strong>Spatial Clustering:</strong> Businesses are densely concentrated in central and eastern regions (Downtown, Geylang, Bedok, Tampines). Western catchment, Lim Chu Kang, and offshore islands show minimal registrations.</li>
<li><strong>Category Mix:</strong> Service-oriented F&amp;B dominate urban areas, while manufacturing clusters are more peripheral.</li>
</ul>
</div>
</div>
</section>
<section id="first-order-spatial-and-spatio-temporal-patterns-analysis" class="level1">
<h1><strong>4 First-order Spatial and Spatio-Temporal Patterns Analysis</strong></h1>
<section id="computing-kernel-density-estimation-kde" class="level2">
<h2 class="anchored" data-anchor-id="computing-kernel-density-estimation-kde"><strong>4.1 Computing kernel density estimation (KDE)</strong></h2>
<p>We will compute the kernel density estimate (KDE) for each business types using <code>bw.ppl</code>:</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>to_ppp <span class="ot">&lt;-</span> <span class="cf">function</span>(sf_points, window_W) {</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>  sf_points <span class="ot">&lt;-</span> <span class="fu">st_transform</span>(sf_points, <span class="dv">3414</span>)</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>  coords <span class="ot">&lt;-</span> <span class="fu">st_coordinates</span>(sf_points)</span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ppp</span>(<span class="at">x =</span> coords[,<span class="dv">1</span>], <span class="at">y =</span> coords[,<span class="dv">2</span>], <span class="at">window =</span> window_W, <span class="at">checkdup =</span> <span class="cn">FALSE</span>)</span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a>ppp_all  <span class="ot">&lt;-</span> <span class="fu">to_ppp</span>(acra_all_fnb_sf, sg_owin)</span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a>ppp_56   <span class="ot">&lt;-</span> <span class="fu">to_ppp</span>(biz_56_sf, sg_owin)</span>
<span id="cb22-9"><a href="#cb22-9" aria-hidden="true" tabindex="-1"></a>ppp_107  <span class="ot">&lt;-</span> <span class="fu">to_ppp</span>(biz_107_sf, sg_owin)</span>
<span id="cb22-10"><a href="#cb22-10" aria-hidden="true" tabindex="-1"></a>ppp_110  <span class="ot">&lt;-</span> <span class="fu">to_ppp</span>(biz_110_sf, sg_owin)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p><strong>All F&amp;B Businesses:</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>ppp_all_km <span class="ot">&lt;-</span> <span class="fu">rescale.ppp</span>(ppp_all, <span class="dv">1000</span>, <span class="st">"km"</span>)</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>bw_all_ppl <span class="ot">&lt;-</span> <span class="fu">density</span>(ppp_all_km,</span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>                          <span class="at">sigma=</span>bw.ppl, </span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>                          <span class="at">edge=</span><span class="cn">TRUE</span>,</span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a>                          <span class="at">kernel=</span><span class="st">"gaussian"</span>)</span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-8"><a href="#cb23-8" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(bw_all_ppl, <span class="at">main =</span> <span class="st">"Intensity (KDE) — All F&amp;B"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="takehome_ex1_files/figure-html/unnamed-chunk-24-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="Observation">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Observation
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li><p><strong>Hotspot clearly visible in central Singapore (CBD / Orchard / Bugis area)</strong> — shown by the yellow–red cluster.</p></li>
<li><p>Other <strong>moderate hotspots</strong> appear in the east (Tampines, Pasir Ris) and north-east (Hougang, Serangoon).</p></li>
<li><p>The west and north (Jurong, Woodlands, Yishun) show <strong>lower but non-zero intensity</strong>.</p></li>
<li><p>Interpretation: F&amp;B registrations are <strong>heavily concentrated in commercial core and mature regional centers</strong>, consistent with population density and retail activity.</p></li>
</ul>
</div>
</div>
<p><strong>By business group:</strong></p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>ppp_56_km <span class="ot">&lt;-</span> <span class="fu">rescale.ppp</span>(ppp_56, <span class="dv">1000</span>, <span class="st">"km"</span>)</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>ppp_107_km <span class="ot">&lt;-</span> <span class="fu">rescale.ppp</span>(ppp_107, <span class="dv">1000</span>, <span class="st">"km"</span>)</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>ppp_110_km <span class="ot">&lt;-</span> <span class="fu">rescale.ppp</span>(ppp_110, <span class="dv">1000</span>, <span class="st">"km"</span>)</span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>bw_56_ppl <span class="ot">&lt;-</span> <span class="fu">density</span>(ppp_56_km,</span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a>                          <span class="at">sigma=</span>bw.ppl, </span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a>                          <span class="at">edge=</span><span class="cn">TRUE</span>,</span>
<span id="cb24-8"><a href="#cb24-8" aria-hidden="true" tabindex="-1"></a>                          <span class="at">kernel=</span><span class="st">"gaussian"</span>)</span>
<span id="cb24-9"><a href="#cb24-9" aria-hidden="true" tabindex="-1"></a>bw_107_ppl <span class="ot">&lt;-</span> <span class="fu">density</span>(ppp_107_km,</span>
<span id="cb24-10"><a href="#cb24-10" aria-hidden="true" tabindex="-1"></a>                          <span class="at">sigma=</span>bw.ppl, </span>
<span id="cb24-11"><a href="#cb24-11" aria-hidden="true" tabindex="-1"></a>                          <span class="at">edge=</span><span class="cn">TRUE</span>,</span>
<span id="cb24-12"><a href="#cb24-12" aria-hidden="true" tabindex="-1"></a>                          <span class="at">kernel=</span><span class="st">"gaussian"</span>)</span>
<span id="cb24-13"><a href="#cb24-13" aria-hidden="true" tabindex="-1"></a>bw_110_ppl <span class="ot">&lt;-</span> <span class="fu">density</span>(ppp_110_km,</span>
<span id="cb24-14"><a href="#cb24-14" aria-hidden="true" tabindex="-1"></a>                          <span class="at">sigma=</span>bw.ppl, </span>
<span id="cb24-15"><a href="#cb24-15" aria-hidden="true" tabindex="-1"></a>                          <span class="at">edge=</span><span class="cn">TRUE</span>,</span>
<span id="cb24-16"><a href="#cb24-16" aria-hidden="true" tabindex="-1"></a>                          <span class="at">kernel=</span><span class="st">"gaussian"</span>)</span>
<span id="cb24-17"><a href="#cb24-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-18"><a href="#cb24-18" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">3</span>))</span>
<span id="cb24-19"><a href="#cb24-19" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(bw_56_ppl, <span class="at">main =</span> <span class="st">"Div 56"</span>)</span>
<span id="cb24-20"><a href="#cb24-20" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(bw_107_ppl, <span class="at">main =</span> <span class="st">"Grp 107"</span>)</span>
<span id="cb24-21"><a href="#cb24-21" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(bw_110_ppl, <span class="at">main =</span> <span class="st">"Grp 110"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="takehome_ex1_files/figure-html/unnamed-chunk-25-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div id="Takeaways" class="callout callout-style-default callout-note callout-titled" title="Takeaways">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Takeaways
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li><p>Div 56 &gt;&gt; Grp 107 &gt;&gt; Grp 110 in terms of density scale.</p></li>
<li><p>All three categories cluster in/around central Singapore, but with different intensity:</p>
<ul>
<li><p>F&amp;B (Div 56) → very widespread, many neighborhoods.</p></li>
<li><p>Food Manufacturing (Grp 107) → narrow CBD/airport-focused.</p></li>
<li><p>Beverages Manufacturing (Grp 110) → very sparse, niche clustering.</p></li>
</ul></li>
<li><p>This suggest F&amp;B is <strong>saturated in the core</strong>, while FM is more tight, and BM remain <strong>specialized</strong>.</p></li>
</ul>
</div>
</div>
</section>
<section id="spatio-temporal-kde-mapping" class="level2">
<h2 class="anchored" data-anchor-id="spatio-temporal-kde-mapping"><strong>4.2 Spatio-Temporal KDE Mapping</strong></h2>
<p><strong>Visualizing New F&amp;B/Hospitality Registrations by Month</strong></p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>acra_all_fnb_sf <span class="ot">&lt;-</span> acra_all_fnb_sf <span class="sc">%&gt;%</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">date =</span> <span class="fu">as.Date</span>(date),</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">month =</span> <span class="fu">floor_date</span>(date, <span class="st">"month"</span>))</span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>months_seq   <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="fu">as.Date</span>(<span class="st">"2024-01-01"</span>), <span class="fu">as.Date</span>(<span class="st">"2025-06-01"</span>), <span class="at">by =</span> <span class="st">"1 month"</span>)</span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a>month_levels <span class="ot">&lt;-</span> <span class="fu">format</span>(months_seq, <span class="st">"%b-%Y"</span>)</span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-8"><a href="#cb25-8" aria-hidden="true" tabindex="-1"></a>acra_all_fnb_sf <span class="ot">&lt;-</span> acra_all_fnb_sf <span class="sc">%&gt;%</span></span>
<span id="cb25-9"><a href="#cb25-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">month_f =</span> <span class="fu">format</span>(month, <span class="st">"%b-%Y"</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb25-10"><a href="#cb25-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(month <span class="sc">%in%</span> months_seq) <span class="sc">%&gt;%</span></span>
<span id="cb25-11"><a href="#cb25-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">month_f =</span> <span class="fu">factor</span>(month_f, <span class="at">levels =</span> month_levels)) <span class="sc">%&gt;%</span></span>
<span id="cb25-12"><a href="#cb25-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(month_f))</span>
<span id="cb25-13"><a href="#cb25-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-14"><a href="#cb25-14" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(acra_all_fnb_sf) <span class="sc">+</span></span>
<span id="cb25-15"><a href="#cb25-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_sf</span>(<span class="at">size =</span> <span class="fl">0.1</span>) <span class="sc">+</span></span>
<span id="cb25-16"><a href="#cb25-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_sf</span>(<span class="at">data =</span> sg_bound, <span class="at">fill =</span> <span class="cn">NA</span>, <span class="at">color =</span> <span class="st">"grey50"</span>, <span class="at">linewidth =</span> <span class="fl">0.2</span>, <span class="at">inherit.aes =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb25-17"><a href="#cb25-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span> month_f, <span class="at">ncol =</span> <span class="dv">4</span>) <span class="sc">+</span></span>
<span id="cb25-18"><a href="#cb25-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"New F&amp;B/Hospitality Registrations by Month"</span>,</span>
<span id="cb25-19"><a href="#cb25-19" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="cn">NULL</span>, <span class="at">y =</span> <span class="cn">NULL</span>) <span class="sc">+</span></span>
<span id="cb25-20"><a href="#cb25-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>(<span class="at">base_size =</span> <span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="takehome_ex1_files/figure-html/unnamed-chunk-26-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co">#monthly points</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>pts <span class="ot">&lt;-</span> <span class="fu">st_transform</span>(acra_all_fnb_sf, <span class="dv">3414</span>) <span class="sc">|&gt;</span></span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(date)) <span class="sc">|&gt;</span></span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">month =</span> <span class="fu">floor_date</span>(date, <span class="st">"month"</span>))</span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a><span class="co">#KDE for a given month</span></span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a>kde_one_month <span class="ot">&lt;-</span> <span class="cf">function</span>(sf_points, window, <span class="at">sigma =</span> <span class="dv">500</span>) {</span>
<span id="cb26-8"><a href="#cb26-8" aria-hidden="true" tabindex="-1"></a>  M <span class="ot">&lt;-</span> <span class="fu">st_coordinates</span>(sf_points)</span>
<span id="cb26-9"><a href="#cb26-9" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> (<span class="fu">nrow</span>(M) <span class="sc">&lt;</span> <span class="dv">3</span>) <span class="fu">return</span>(<span class="cn">NULL</span>)</span>
<span id="cb26-10"><a href="#cb26-10" aria-hidden="true" tabindex="-1"></a>  p <span class="ot">&lt;-</span> <span class="fu">ppp</span>(M[,<span class="dv">1</span>], M[,<span class="dv">2</span>], <span class="at">window =</span> window)</span>
<span id="cb26-11"><a href="#cb26-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">density</span>(p, <span class="at">sigma =</span> sigma, <span class="at">edge =</span> <span class="cn">TRUE</span>)</span>
<span id="cb26-12"><a href="#cb26-12" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb26-13"><a href="#cb26-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-14"><a href="#cb26-14" aria-hidden="true" tabindex="-1"></a><span class="co"># KDE for one month </span></span>
<span id="cb26-15"><a href="#cb26-15" aria-hidden="true" tabindex="-1"></a>kde_one_month <span class="ot">&lt;-</span> <span class="cf">function</span>(sf_points, window, <span class="at">sigma =</span> <span class="dv">500</span>) {</span>
<span id="cb26-16"><a href="#cb26-16" aria-hidden="true" tabindex="-1"></a>  M <span class="ot">&lt;-</span> <span class="fu">st_coordinates</span>(sf_points)</span>
<span id="cb26-17"><a href="#cb26-17" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> (<span class="fu">nrow</span>(M) <span class="sc">&lt;</span> <span class="dv">3</span>) <span class="fu">return</span>(<span class="cn">NULL</span>)               </span>
<span id="cb26-18"><a href="#cb26-18" aria-hidden="true" tabindex="-1"></a>  p <span class="ot">&lt;-</span> <span class="fu">ppp</span>(M[,<span class="dv">1</span>], M[,<span class="dv">2</span>], <span class="at">window =</span> window)</span>
<span id="cb26-19"><a href="#cb26-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">density</span>(p, <span class="at">sigma =</span> sigma, <span class="at">edge =</span> <span class="cn">TRUE</span>)      </span>
<span id="cb26-20"><a href="#cb26-20" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb26-21"><a href="#cb26-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-22"><a href="#cb26-22" aria-hidden="true" tabindex="-1"></a><span class="co"># KDEs for all 18 months</span></span>
<span id="cb26-23"><a href="#cb26-23" aria-hidden="true" tabindex="-1"></a>kde_by_month <span class="ot">&lt;-</span> <span class="fu">lapply</span>(months_seq, <span class="cf">function</span>(m0) {</span>
<span id="cb26-24"><a href="#cb26-24" aria-hidden="true" tabindex="-1"></a>  m_pts <span class="ot">&lt;-</span> pts <span class="sc">|&gt;</span> <span class="fu">filter</span>(month <span class="sc">==</span> m0)</span>
<span id="cb26-25"><a href="#cb26-25" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kde_one_month</span>(m_pts, sg_owin, <span class="at">sigma =</span> <span class="dv">500</span>)   </span>
<span id="cb26-26"><a href="#cb26-26" aria-hidden="true" tabindex="-1"></a>})</span>
<span id="cb26-27"><a href="#cb26-27" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(kde_by_month) <span class="ot">&lt;-</span> month_levels</span>
<span id="cb26-28"><a href="#cb26-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-29"><a href="#cb26-29" aria-hidden="true" tabindex="-1"></a>plot_kde_grid <span class="ot">&lt;-</span> <span class="cf">function</span>(kde_list, labels, idx, <span class="at">nrow =</span> <span class="dv">4</span>, <span class="at">ncol =</span> <span class="dv">4</span>, <span class="at">main_prefix =</span> <span class="st">"KDE"</span>) {</span>
<span id="cb26-30"><a href="#cb26-30" aria-hidden="true" tabindex="-1"></a>  old_par <span class="ot">&lt;-</span> <span class="fu">par</span>(<span class="at">no.readonly =</span> <span class="cn">TRUE</span>)</span>
<span id="cb26-31"><a href="#cb26-31" aria-hidden="true" tabindex="-1"></a>  <span class="fu">on.exit</span>(<span class="fu">par</span>(old_par))</span>
<span id="cb26-32"><a href="#cb26-32" aria-hidden="true" tabindex="-1"></a>  <span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(nrow, ncol), <span class="at">mar =</span> <span class="fu">c</span>(<span class="fl">1.5</span>, <span class="fl">1.5</span>, <span class="dv">2</span>, <span class="dv">1</span>))</span>
<span id="cb26-33"><a href="#cb26-33" aria-hidden="true" tabindex="-1"></a>  <span class="cf">for</span> (i <span class="cf">in</span> idx) {</span>
<span id="cb26-34"><a href="#cb26-34" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> (i <span class="sc">&gt;</span> <span class="fu">length</span>(kde_list)) { <span class="fu">frame</span>(); <span class="cf">next</span> }</span>
<span id="cb26-35"><a href="#cb26-35" aria-hidden="true" tabindex="-1"></a>    z <span class="ot">&lt;-</span> kde_list[[i]]</span>
<span id="cb26-36"><a href="#cb26-36" aria-hidden="true" tabindex="-1"></a>    ttl <span class="ot">&lt;-</span> labels[i]</span>
<span id="cb26-37"><a href="#cb26-37" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> (<span class="fu">is.null</span>(z)) {</span>
<span id="cb26-38"><a href="#cb26-38" aria-hidden="true" tabindex="-1"></a>      <span class="fu">frame</span>()</span>
<span id="cb26-39"><a href="#cb26-39" aria-hidden="true" tabindex="-1"></a>      <span class="fu">title</span>(<span class="fu">paste0</span>(ttl, <span class="st">"</span><span class="sc">\n</span><span class="st">(no data)"</span>), <span class="at">cex.main =</span> <span class="fl">0.9</span>)</span>
<span id="cb26-40"><a href="#cb26-40" aria-hidden="true" tabindex="-1"></a>    } <span class="cf">else</span> {</span>
<span id="cb26-41"><a href="#cb26-41" aria-hidden="true" tabindex="-1"></a>      <span class="fu">plot</span>(z, <span class="at">main =</span> <span class="fu">paste0</span>(main_prefix, <span class="st">" – "</span>, ttl))</span>
<span id="cb26-42"><a href="#cb26-42" aria-hidden="true" tabindex="-1"></a>      <span class="fu">plot</span>(sg_owin, <span class="at">add =</span> <span class="cn">TRUE</span>)</span>
<span id="cb26-43"><a href="#cb26-43" aria-hidden="true" tabindex="-1"></a>    }</span>
<span id="cb26-44"><a href="#cb26-44" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb26-45"><a href="#cb26-45" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb26-46"><a href="#cb26-46" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-47"><a href="#cb26-47" aria-hidden="true" tabindex="-1"></a><span class="fu">plot_kde_grid</span>(kde_by_month, month_levels, <span class="at">idx =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">16</span>, <span class="at">nrow =</span> <span class="dv">4</span>, <span class="at">ncol =</span> <span class="dv">4</span>, <span class="at">main_prefix =</span> <span class="st">"F&amp;B KDE"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="takehome_ex1_files/figure-html/unnamed-chunk-27-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot_kde_grid</span>(kde_by_month, month_levels, <span class="at">idx =</span> <span class="dv">17</span><span class="sc">:</span><span class="dv">18</span>, <span class="at">nrow =</span> <span class="dv">2</span>, <span class="at">ncol =</span> <span class="dv">2</span>, <span class="at">main_prefix =</span> <span class="st">"F&amp;B KDE"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="takehome_ex1_files/figure-html/unnamed-chunk-27-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>Spatio-temporal KDE mapping (Jan 2024 – Jun 2025) shows that new F&amp;B and manufacturing businesses consistently cluster in Singapore’s central region, with intermittent strengthening in regional centres such as Tampines and Jurong East. The spatial pattern is stable across time, with only intensity fluctuating, suggesting sustained <strong>central dominance</strong> but gradual suburban spillover.</p>
</div>
</div>
</section>
<section id="quadrat-counts-chi-squared-test-of-csr-using-quadrat-counts" class="level2">
<h2 class="anchored" data-anchor-id="quadrat-counts-chi-squared-test-of-csr-using-quadrat-counts"><strong>4.3 Quadrat counts &amp; Chi-squared test of CSR using quadrat counts</strong></h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>Q <span class="ot">&lt;-</span> <span class="fu">quadratcount</span>(ppp_all, <span class="at">nx =</span> <span class="dv">10</span>, <span class="at">ny =</span> <span class="dv">10</span>)     </span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(Q, <span class="at">main =</span> <span class="st">"Quadrat counts – All F&amp;B"</span>); <span class="fu">plot</span>(ppp_all, <span class="at">add =</span> <span class="cn">TRUE</span>, <span class="at">pch=</span><span class="dv">20</span>, <span class="at">cex=</span>.<span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="takehome_ex1_files/figure-html/unnamed-chunk-28-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">quadrat.test</span>(ppp_all, <span class="at">nx =</span> <span class="dv">10</span>, <span class="at">ny =</span> <span class="dv">10</span>)          </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Chi-squared test of CSR using quadrat counts

data:  ppp_all
X2 = 10005, df = 74, p-value &lt; 2.2e-16
alternative hypothesis: two.sided

Quadrats: 75 tiles (irregular windows)</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="Conclusion">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Conclusion
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Reject CSR:</strong> The observed pattern is <strong>not random</strong>; instead, it reflects <strong>significant clustering and spatial heterogeneity</strong>.</p>
</div>
</div>
<p><strong>Choropleth map:</strong></p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>pts_all <span class="ot">&lt;-</span> <span class="fu">st_transform</span>(acra_all_fnb_sf, <span class="dv">3414</span>)</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>bound <span class="ot">&lt;-</span> <span class="fu">st_as_sf</span>(sg_bound) <span class="sc">|&gt;</span> <span class="fu">st_transform</span>(<span class="dv">3414</span>)</span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>grid <span class="ot">&lt;-</span> <span class="fu">st_make_grid</span>(bound, <span class="at">n =</span> <span class="fu">c</span>(<span class="dv">10</span>, <span class="dv">10</span>), <span class="at">square =</span> <span class="cn">TRUE</span>) <span class="sc">|&gt;</span></span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_as_sf</span>() <span class="sc">|&gt;</span></span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">id =</span> <span class="fu">row_number</span>())</span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-7"><a href="#cb31-7" aria-hidden="true" tabindex="-1"></a>cnt <span class="ot">&lt;-</span> <span class="fu">lengths</span>(<span class="fu">st_intersects</span>(grid, pts_all))</span>
<span id="cb31-8"><a href="#cb31-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-9"><a href="#cb31-9" aria-hidden="true" tabindex="-1"></a>Qsf <span class="ot">&lt;-</span> grid <span class="sc">|&gt;</span></span>
<span id="cb31-10"><a href="#cb31-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb31-11"><a href="#cb31-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">counts   =</span> cnt,</span>
<span id="cb31-12"><a href="#cb31-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">area_km2 =</span> <span class="fu">as.numeric</span>(<span class="fu">st_area</span>(grid)) <span class="sc">/</span> <span class="fl">1e6</span>, </span>
<span id="cb31-13"><a href="#cb31-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">dens_km2 =</span> counts <span class="sc">/</span> area_km2</span>
<span id="cb31-14"><a href="#cb31-14" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb31-15"><a href="#cb31-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-16"><a href="#cb31-16" aria-hidden="true" tabindex="-1"></a><span class="fu">tmap_mode</span>(<span class="st">"plot"</span>)</span>
<span id="cb31-17"><a href="#cb31-17" aria-hidden="true" tabindex="-1"></a><span class="fu">tm_shape</span>(Qsf) <span class="sc">+</span></span>
<span id="cb31-18"><a href="#cb31-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_polygons</span>(<span class="st">"counts"</span>, <span class="at">palette =</span> <span class="st">"YlOrRd"</span>, <span class="at">style =</span> <span class="st">"quantile"</span>,</span>
<span id="cb31-19"><a href="#cb31-19" aria-hidden="true" tabindex="-1"></a>              <span class="at">title =</span> <span class="st">"F&amp;B Counts per Cell"</span>) <span class="sc">+</span></span>
<span id="cb31-20"><a href="#cb31-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_shape</span>(bound) <span class="sc">+</span> <span class="fu">tm_borders</span>(<span class="at">col =</span> <span class="st">"grey40"</span>) <span class="sc">+</span></span>
<span id="cb31-21"><a href="#cb31-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_layout</span>(<span class="at">main.title =</span> <span class="st">"Quadrat Counts (All F&amp;B Businesses)"</span>,</span>
<span id="cb31-22"><a href="#cb31-22" aria-hidden="true" tabindex="-1"></a>            <span class="at">legend.outside =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="takehome_ex1_files/figure-html/unnamed-chunk-29-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li><p>Central quadrats (esp.&nbsp;CBD, Orchard, Bugis, and parts of Geylang) have <strong>very high counts</strong>.</p></li>
<li><p>Peripheral quadrats (northern/northwest like Lim Chu Kang, southern islands, western industrial areas) have <strong>very few or zero businesses</strong>.</p></li>
<li><p>The <strong>distribution is highly uneven</strong>, with clustering in central and regional hubs.</p></li>
</ul>
</div>
</div>
<p>Quadrat analysis of all F&amp;B businesses reveals strong spatial heterogeneity. Counts are heavily concentrated in central quadrats (CBD, Orchard, Geylang), while peripheral quadrats often contain few or no businesses. The Chi-squared test of CSR (X² = 10,005, p &lt; 0.001) strongly rejects randomness, confirming that F&amp;B business locations are spatially clustered rather than evenly or randomly distributed.</p>
</section>
</section>
<section id="second-order-spatial-and-spatio-temporal-patterns-analysis" class="level1">
<h1><strong>5 Second-order Spatial and Spatio-Temporal Patterns Analysis</strong></h1>
<section id="clark-evan-test-for-nearest-neighbour-analysis" class="level2">
<h2 class="anchored" data-anchor-id="clark-evan-test-for-nearest-neighbour-analysis"><strong>5.1 Clark-Evan Test for Nearest Neighbour Analysis</strong></h2>
<p>We will perform the Clark-Evans test of aggregation for a spatial point pattern using the&nbsp;<code>clarkevans.test()</code>&nbsp;function from the&nbsp;<strong><code>spatstat</code></strong>&nbsp;package.</p>
<div class="callout callout-style-default callout-note callout-titled" title="Test Hypotheses">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Test Hypotheses
</div>
</div>
<div class="callout-body-container callout-body">
<p>Ho = The distribution of F&amp;B businesses are randomly distributed.</p>
<p>H<sub>1</sub>= The distribution of F&amp;B businesses are not randomly distributed.</p>
<p>The 95% confident interval will be used.</p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">clarkevans.test</span>(ppp_all, <span class="at">correction=</span><span class="st">"none"</span>, <span class="at">clipregion=</span><span class="st">"sg_owin"</span>,             <span class="at">alternative=</span><span class="fu">c</span>(<span class="st">"clustered"</span>), <span class="at">method=</span><span class="st">"MonteCarlo"</span>, <span class="at">nsim=</span><span class="dv">99</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Clark-Evans test
    No edge correction
    Monte Carlo test based on 99 simulations of CSR with fixed n

data:  ppp_all
R = 0.32706, p-value = 0.01
alternative hypothesis: clustered (R &lt; 1)</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="Conclusion">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Conclusion
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Reject H₀</strong>. The distribution of F&amp;B businesses is <strong>statistically significantly clustered, not random</strong>. This clustering is likely tied to underlying factors such as high population density in urban areas or specific government’s planning.</p>
</div>
</div>
</section>
<section id="spatial-point-patterns-analysis-methods" class="level2">
<h2 class="anchored" data-anchor-id="spatial-point-patterns-analysis-methods"><strong>5.2 Spatial Point Patterns Analysis Methods</strong></h2>
<p>We will perform some SPPA methods to confirm on the above takeaways.</p>
<p><strong>G-function (nearest-neighbour distribution)</strong></p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>pp_range_all <span class="ot">&lt;-</span> ppp_all           </span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>lambda <span class="ot">&lt;-</span> <span class="fu">intensity</span>(ppp_all)</span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>r_nn <span class="ot">&lt;-</span> <span class="dv">1</span><span class="sc">/</span>(<span class="dv">2</span><span class="sc">*</span><span class="fu">sqrt</span>(lambda))</span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a>rmax  <span class="ot">&lt;-</span> <span class="dv">3</span> <span class="sc">*</span> r_nn               </span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a>rseq  <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="dv">0</span>, rmax, <span class="at">length.out =</span> <span class="dv">64</span>)  </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>G_all <span class="ot">&lt;-</span> <span class="fu">Gest</span>(ppp_all, <span class="at">r=</span>rseq)</span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>G_56 <span class="ot">&lt;-</span> <span class="fu">Gest</span>(ppp_56, <span class="at">r=</span>rseq) </span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>G_107 <span class="ot">&lt;-</span> <span class="fu">Gest</span>(ppp_107, <span class="at">r=</span>rseq) </span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a>G_110 <span class="ot">&lt;-</span> <span class="fu">Gest</span>(ppp_110, <span class="at">r=</span>rseq) </span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-6"><a href="#cb35-6" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">2</span>))</span>
<span id="cb35-7"><a href="#cb35-7" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(G_all)</span>
<span id="cb35-8"><a href="#cb35-8" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(G_56)</span>
<span id="cb35-9"><a href="#cb35-9" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(G_107)</span>
<span id="cb35-10"><a href="#cb35-10" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(G_110)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="takehome_ex1_files/figure-html/unnamed-chunk-32-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li><p>These plots confirms that overall F&amp;B/manufacturing businesses, especially restaurants (Div 56), show strong clustering at small distances, consistent with dense food hubs and mall-based concentration.</p></li>
<li><p>Food Manufacturing (Grp 107) shows clustering at broader scales. (100–300 m)</p></li>
<li><p>Beverages Manufacturing (Grp 110) appear more randomly distributed due to their limited counts.</p></li>
</ul>
</div>
</div>
<p><strong>Pair correlation (local interactions)</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>pcf_all <span class="ot">&lt;-</span> <span class="fu">pcf</span>(ppp_all, <span class="at">r=</span>rseq, <span class="at">correction=</span><span class="st">"translation"</span>)</span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>pcf_56 <span class="ot">&lt;-</span> <span class="fu">pcf</span>(ppp_56, <span class="at">r=</span>rseq, <span class="at">correction=</span><span class="st">"translation"</span>)</span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>pcf_107 <span class="ot">&lt;-</span> <span class="fu">pcf</span>(ppp_107, <span class="at">r=</span>rseq, <span class="at">correction=</span><span class="st">"translation"</span>)</span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a>pcf_110 <span class="ot">&lt;-</span> <span class="fu">pcf</span>(ppp_110, <span class="at">r=</span>rseq, <span class="at">correction=</span><span class="st">"translation"</span>)</span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-6"><a href="#cb36-6" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">2</span>))</span>
<span id="cb36-7"><a href="#cb36-7" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(pcf_all)</span>
<span id="cb36-8"><a href="#cb36-8" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(pcf_56)</span>
<span id="cb36-9"><a href="#cb36-9" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(pcf_107)</span>
<span id="cb36-10"><a href="#cb36-10" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(pcf_110)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="takehome_ex1_files/figure-html/unnamed-chunk-33-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>Pair correlation functions (PCF) again confirm strong short-range clustering. (Div 56) are highly concentrated within 0–50 m, (Grp 107) shows clustering at broader scales (up to ~200 m), (Grp 110) display weaker or near-random distribution.</p>
</div>
</div>
<p><strong>Inhomogeneous K-function</strong></p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>bw_all_dg  <span class="ot">&lt;-</span> <span class="fu">bw.diggle</span>(ppp_all)</span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>rho_all <span class="ot">&lt;-</span> <span class="fu">density</span>(ppp_all)</span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>Ki_all  <span class="ot">&lt;-</span> <span class="fu">Kinhom</span>(ppp_all, <span class="at">lambda =</span> rho_all)</span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a>bw_56_dg  <span class="ot">&lt;-</span> <span class="fu">bw.diggle</span>(ppp_56)</span>
<span id="cb37-6"><a href="#cb37-6" aria-hidden="true" tabindex="-1"></a>rho_56 <span class="ot">&lt;-</span> <span class="fu">density</span>(ppp_56)</span>
<span id="cb37-7"><a href="#cb37-7" aria-hidden="true" tabindex="-1"></a>Ki_56  <span class="ot">&lt;-</span> <span class="fu">Kinhom</span>(ppp_56, <span class="at">lambda =</span> rho_56)</span>
<span id="cb37-8"><a href="#cb37-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-9"><a href="#cb37-9" aria-hidden="true" tabindex="-1"></a>bw_107_dg  <span class="ot">&lt;-</span> <span class="fu">bw.diggle</span>(ppp_107)</span>
<span id="cb37-10"><a href="#cb37-10" aria-hidden="true" tabindex="-1"></a>rho_107 <span class="ot">&lt;-</span> <span class="fu">density</span>(ppp_107)</span>
<span id="cb37-11"><a href="#cb37-11" aria-hidden="true" tabindex="-1"></a>Ki_107  <span class="ot">&lt;-</span> <span class="fu">Kinhom</span>(ppp_107, <span class="at">lambda =</span> rho_107)</span>
<span id="cb37-12"><a href="#cb37-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-13"><a href="#cb37-13" aria-hidden="true" tabindex="-1"></a>bw_110_dg  <span class="ot">&lt;-</span> <span class="fu">bw.diggle</span>(ppp_110)</span>
<span id="cb37-14"><a href="#cb37-14" aria-hidden="true" tabindex="-1"></a>rho_110 <span class="ot">&lt;-</span> <span class="fu">density</span>(ppp_110)</span>
<span id="cb37-15"><a href="#cb37-15" aria-hidden="true" tabindex="-1"></a>Ki_110  <span class="ot">&lt;-</span> <span class="fu">Kinhom</span>(ppp_110, <span class="at">lambda =</span> rho_110)</span>
<span id="cb37-16"><a href="#cb37-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-17"><a href="#cb37-17" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">2</span>))</span>
<span id="cb37-18"><a href="#cb37-18" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(Ki_all, <span class="at">main =</span> <span class="st">"Inhomogeneous K – All F&amp;B"</span>)</span>
<span id="cb37-19"><a href="#cb37-19" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(Ki_56, <span class="at">main =</span> <span class="st">"Div 56"</span>)</span>
<span id="cb37-20"><a href="#cb37-20" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(Ki_107, <span class="at">main =</span> <span class="st">"Grp 107"</span>)</span>
<span id="cb37-21"><a href="#cb37-21" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(Ki_110, <span class="at">main =</span> <span class="st">"Grp 110"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p><img src="../..\images/inhomogeneous k.png" class="img-fluid"></p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>F&amp;B businesses and restaurants (Div 56) remain significantly clustered at local-to-regional scales (up to ~3 km). (Grp 107) show weaker clustering, visible mainly at broader scales (&gt;4 km). (Grp 110) appear nearly random.</p>
</div>
</div>
</section>
<section id="spatio-temporal-point-patterns-analysis-methods" class="level2">
<h2 class="anchored" data-anchor-id="spatio-temporal-point-patterns-analysis-methods"><strong>5.3 Spatio-temporal Point Patterns Analysis Methods</strong></h2>
<p>We will reveal businesses clustering in both space and time simultaneously.</p>
<p><strong>Homogeneous STIK Method</strong></p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>sg_bound <span class="ot">&lt;-</span> sg_bound <span class="sc">%&gt;%</span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_union</span>() <span class="sc">%&gt;%</span></span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_transform</span>(<span class="dv">3414</span>)</span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a>s.region <span class="ot">&lt;-</span> <span class="fu">st_coordinates</span>(sg_bound)[, <span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>]</span>
<span id="cb38-6"><a href="#cb38-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-7"><a href="#cb38-7" aria-hidden="true" tabindex="-1"></a>pts_sf <span class="ot">&lt;-</span> <span class="fu">st_transform</span>(acra_all_fnb_sf, <span class="dv">3414</span>) <span class="sc">|&gt;</span></span>
<span id="cb38-8"><a href="#cb38-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(date))</span>
<span id="cb38-9"><a href="#cb38-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-10"><a href="#cb38-10" aria-hidden="true" tabindex="-1"></a>XY   <span class="ot">&lt;-</span> <span class="fu">st_coordinates</span>(pts_sf)</span>
<span id="cb38-11"><a href="#cb38-11" aria-hidden="true" tabindex="-1"></a>t0   <span class="ot">&lt;-</span> <span class="fu">min</span>(<span class="fu">as.Date</span>(pts_sf<span class="sc">$</span>date), <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb38-12"><a href="#cb38-12" aria-hidden="true" tabindex="-1"></a>tday <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(<span class="fu">as.Date</span>(pts_sf<span class="sc">$</span>date) <span class="sc">-</span> t0)   </span>
<span id="cb38-13"><a href="#cb38-13" aria-hidden="true" tabindex="-1"></a>xyt <span class="ot">&lt;-</span> <span class="fu">as.3dpoints</span>(<span class="at">x =</span> XY[,<span class="dv">1</span>], <span class="at">y =</span> XY[,<span class="dv">2</span>], <span class="at">t =</span> tday)   </span>
<span id="cb38-14"><a href="#cb38-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-15"><a href="#cb38-15" aria-hidden="true" tabindex="-1"></a>u <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">1500</span>, <span class="at">by =</span> <span class="dv">100</span>)  </span>
<span id="cb38-16"><a href="#cb38-16" aria-hidden="true" tabindex="-1"></a>v <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="dv">0</span>,   <span class="dv">90</span>, <span class="at">by =</span>   <span class="dv">7</span>)  </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Homogeneous STIK (quick baseline)</span></span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>stik_hom <span class="ot">&lt;-</span> <span class="fu">STIKhat</span>(</span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">xyt      =</span> xyt,</span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">s.region =</span> s.region,</span>
<span id="cb39-5"><a href="#cb39-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">t.region =</span> <span class="fu">range</span>(tday, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb39-6"><a href="#cb39-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">dist     =</span> u,</span>
<span id="cb39-7"><a href="#cb39-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">times    =</span> v,</span>
<span id="cb39-8"><a href="#cb39-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">correction =</span> <span class="st">"isotropic"</span></span>
<span id="cb39-9"><a href="#cb39-9" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb39-10"><a href="#cb39-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-11"><a href="#cb39-11" aria-hidden="true" tabindex="-1"></a><span class="fu">plotK</span>(stik_hom, <span class="at">type =</span> <span class="st">"contour"</span>, <span class="at">legend =</span> <span class="cn">TRUE</span>, <span class="at">main =</span> <span class="st">"STIK (homogeneous)"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><img src="../..\images/stik_homogenious.png" class="img-fluid"></p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>Homogeneous STIK analysis for all F&amp;B businesses indicates that spatio-temporal clustering is not clear at small scales (≤500 m, ≤30 days). Clustering becomes evident at broader scales, with businesses tending to co-locate within 1–2 km and within 1–3 months of each other. This suggests that new registrations emerge in bursts at the neighbourhood or regional level, rather than in highly localised, short-term clusters.</p>
</div>
</div>
<p><strong>Knox Space–Time Interaction Method</strong></p>
<p>We applied the Knox test across a grid of spatial (200 m – 5 km) and temporal (90 – 180 days) thresholds.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>pts_knox <span class="ot">&lt;-</span> pts_sf <span class="sc">|&gt;</span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">t_days =</span> <span class="fu">as.numeric</span>(date <span class="sc">-</span> <span class="fu">min</span>(date, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)))</span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a>XY <span class="ot">&lt;-</span> <span class="fu">st_coordinates</span>(pts_knox)</span>
<span id="cb40-5"><a href="#cb40-5" aria-hidden="true" tabindex="-1"></a>T  <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(pts_knox<span class="sc">$</span>date <span class="sc">-</span> <span class="fu">min</span>(pts_knox<span class="sc">$</span>date))</span>
<span id="cb40-6"><a href="#cb40-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-7"><a href="#cb40-7" aria-hidden="true" tabindex="-1"></a>knox_result <span class="ot">&lt;-</span> <span class="fu">knox</span>(</span>
<span id="cb40-8"><a href="#cb40-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">coords =</span> XY,         </span>
<span id="cb40-9"><a href="#cb40-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">times  =</span> T,          </span>
<span id="cb40-10"><a href="#cb40-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">ds     =</span> <span class="dv">500</span>,        </span>
<span id="cb40-11"><a href="#cb40-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">dt     =</span> <span class="dv">30</span>,         </span>
<span id="cb40-12"><a href="#cb40-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">method =</span> <span class="st">"bootstrap"</span>,</span>
<span id="cb40-13"><a href="#cb40-13" aria-hidden="true" tabindex="-1"></a>  <span class="at">nsim   =</span> <span class="dv">199</span>,</span>
<span id="cb40-14"><a href="#cb40-14" aria-hidden="true" tabindex="-1"></a>  <span class="at">eps.s  =</span> <span class="fl">1e-6</span>,       </span>
<span id="cb40-15"><a href="#cb40-15" aria-hidden="true" tabindex="-1"></a>  <span class="at">eps.t  =</span> <span class="fl">1e-6</span>        </span>
<span id="cb40-16"><a href="#cb40-16" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>.......................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>knox_result</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
    Knox test with simulated p-value

data:  dt = 30 and ds = 500
number of close pairs = 0, B = 999, p-value = 1
alternative hypothesis: true number is greater than 0

contingency table:
          ds
dt         &lt;= 1e-06  &gt; 1e-06
  &lt;= 1e-06        0        0
   &gt; 1e-06        0        1</code></pre>
</div>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>ds_vals <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">200</span>, <span class="dv">500</span>, <span class="dv">1000</span>, <span class="dv">2000</span>, <span class="dv">5000</span>)   </span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>dt_vals <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">90</span>, <span class="dv">120</span>, <span class="dv">180</span>)       </span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-4"><a href="#cb44-4" aria-hidden="true" tabindex="-1"></a>knox_grid <span class="ot">&lt;-</span> <span class="fu">expand.grid</span>(<span class="at">ds =</span> ds_vals, <span class="at">dt =</span> dt_vals)</span>
<span id="cb44-5"><a href="#cb44-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-6"><a href="#cb44-6" aria-hidden="true" tabindex="-1"></a>results <span class="ot">&lt;-</span> <span class="fu">apply</span>(knox_grid, <span class="dv">1</span>, <span class="cf">function</span>(row) {</span>
<span id="cb44-7"><a href="#cb44-7" aria-hidden="true" tabindex="-1"></a>  k <span class="ot">&lt;-</span> <span class="fu">knox</span>(</span>
<span id="cb44-8"><a href="#cb44-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">coords =</span> XY,</span>
<span id="cb44-9"><a href="#cb44-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">times  =</span> T,</span>
<span id="cb44-10"><a href="#cb44-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">ds     =</span> row[[<span class="st">"ds"</span>]],</span>
<span id="cb44-11"><a href="#cb44-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">dt     =</span> row[[<span class="st">"dt"</span>]],</span>
<span id="cb44-12"><a href="#cb44-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">method =</span> <span class="st">"bootstrap"</span>,</span>
<span id="cb44-13"><a href="#cb44-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">nsim   =</span> <span class="dv">199</span>,</span>
<span id="cb44-14"><a href="#cb44-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">eps.s  =</span> <span class="fl">1e-6</span>, <span class="at">eps.t =</span> <span class="fl">1e-6</span></span>
<span id="cb44-15"><a href="#cb44-15" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb44-16"><a href="#cb44-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">c</span>(<span class="at">ds =</span> row[[<span class="st">"ds"</span>]], <span class="at">dt =</span> row[[<span class="st">"dt"</span>]],</span>
<span id="cb44-17"><a href="#cb44-17" aria-hidden="true" tabindex="-1"></a>    <span class="at">obs =</span> k<span class="sc">$</span>statistic[<span class="st">"observed"</span>],</span>
<span id="cb44-18"><a href="#cb44-18" aria-hidden="true" tabindex="-1"></a>    <span class="at">exp =</span> k<span class="sc">$</span>statistic[<span class="st">"expected"</span>],</span>
<span id="cb44-19"><a href="#cb44-19" aria-hidden="true" tabindex="-1"></a>    <span class="at">p   =</span> k<span class="sc">$</span>p.value)</span>
<span id="cb44-20"><a href="#cb44-20" aria-hidden="true" tabindex="-1"></a>})</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>.......................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
.......................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
.......................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
.......................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
.......................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
.......................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
.......................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
.......................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
.......................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
.......................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
.......................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
.......................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
.......................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
.......................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
.......................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a>knox_df <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(<span class="fu">t</span>(results))</span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(knox_df, <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">factor</span>(ds), <span class="at">y =</span> <span class="fu">factor</span>(dt), <span class="at">fill =</span> p)) <span class="sc">+</span></span>
<span id="cb46-4"><a href="#cb46-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_tile</span>(<span class="at">color =</span> <span class="st">"grey70"</span>) <span class="sc">+</span></span>
<span id="cb46-5"><a href="#cb46-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_viridis_c</span>(<span class="at">option =</span> <span class="st">"plasma"</span>, <span class="at">direction =</span> <span class="sc">-</span><span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb46-6"><a href="#cb46-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Spatial threshold (m)"</span>, <span class="at">y =</span> <span class="st">"Temporal threshold (days)"</span>,</span>
<span id="cb46-7"><a href="#cb46-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">fill =</span> <span class="st">"p-value"</span>,</span>
<span id="cb46-8"><a href="#cb46-8" aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">"Knox test grid: spatio-temporal clustering"</span>) <span class="sc">+</span></span>
<span id="cb46-9"><a href="#cb46-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="takehome_ex1_files/figure-html/unnamed-chunk-38-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>In all cases, the number of observed space–time pairs did not exceed expectation under independence (p ≈ 1). This indicates that while business registrations are <strong>spatially clustered</strong> (as shown by quadrat counts, KDE, G- and K-function analyses), the <strong>timing of registrations is largely independent of spatial proximity</strong>. In other words, businesses open in the same hotspots (CBD, regional centres), but not in bursts within short temporal windows. Spatio-temporal interaction only emerged weakly at broader scales in the STIK analysis (1–2 km, 1–3 months), suggesting neighbourhood-level clustering over longer periods rather than micro-scale space–time surges.</p>
</div>
</div>
</section>
</section>
<section id="discussion-of-results-and-implications-for-urban-planning" class="level1">
<h1><strong>6 Discussion of Results and Implications for Urban Planning</strong></h1>
<section id="results-from-analyses" class="level2">
<h2 class="anchored" data-anchor-id="results-from-analyses"><strong>6.1 Results from Analyses</strong></h2>
<p>The spatial analysis of new F&amp;B and manufacturing businesses in Singapore (Jan 2024–Jun 2025) provides strong evidence of <strong>non-random, clustered distribution patterns</strong>.</p>
<p><strong>First-order analysis</strong> using KDE and quadrat counts revealed strong spatial heterogeneity. Division 56 (F&amp;B services) registrations were highly concentrated in the Central Area (CBD, Orchard, Bugis), with secondary hotspots in mature regional centres such as Tampines and Jurong East. The Chi-squared test of CSR strongly rejected randomness, confirming clustering. By contrast, Group 107 (food manufacturing) and Group 110 (beverage manufacturing) showed much lower intensities overall, with activities concentrated in designated industrial estates rather than dispersed across the urban fabric. These findings reflect Singapore’s established land-use zoning, where F&amp;B retail thrives in high-density commercial and residential zones, while manufacturing is contained within industrial clusters.</p>
<p><strong>Second-order analysis</strong> using Nearest-neighbour functions and pair correlation functions indicated that F&amp;B services (Div 56) exhibit strong clustering at micro-scales (&lt;50–150 m), consistent with hawker centres, malls, and food streets. Food manufacturing (Grp 107) showed clustering at broader scales (200–400 m), corresponding to concentration in specific industrial parks, while beverage manufacturing (Grp 110) displayed near-random or weak clustering, reflecting its niche and relatively small number of firms. Inhomogeneous K-function analysis confirmed that clustering persists for Div 56 even after adjusting for background density, suggesting effects beyond simple population concentration. Spatio-temporal K (STIK) and Knox tests, however, showed no strong evidence of simultaneous space–time clustering at fine scales (≤500 m, ≤30 days). Instead, weak interaction appeared at broader windows (1–2 km and 1–3 months), implying that while new businesses arise in the same hotspots, their registrations are not tightly synchronised in time.</p>
</section>
<section id="implications-for-planning-and-management" class="level2">
<h2 class="anchored" data-anchor-id="implications-for-planning-and-management"><strong>6.2 Implications for planning and management</strong></h2>
<p>First, the persistence of micro-scale clustering in F&amp;B services supports the continued relevance of <strong>mixed-use nodes and neighbourhood centres</strong> in sustaining vibrant food ecosystems. Planning for adequate retail and food spaces in both central and suburban growth areas can reinforce accessibility and reduce over-concentration in the core.</p>
<p>Second, the distinct clustering of food and beverage manufacturing in industrial zones highlights the importance of <strong>protecting and upgrading industrial land parcels</strong> suited for food processing, especially with <strong>Singapore’s “30 by 30” food security strategy</strong>. Spatial monitoring of where such clusters emerge or decline can inform zoning adjustments and targeted infrastructure (e.g., warehouses or cold chain logistics).</p>
<p>Finally, the absence of strong spatio-temporal bursts suggests that business formation is steady rather than boom-and-bust. This provides planners with a relatively predictable trajectory for <strong>incremental provision of facilities</strong>, rather than needing rapid, reactive expansions.</p>
<p>In conclusion, spatial analysis of F&amp;B business formation reveals differentiated patterns between retail services and manufacturing subsectors. Recognising these differences can help planners balance central vibrancy with suburban growth, protect industrial clusters for food production, and support sustainable land use that aligns with Singapore’s broader economic and food security objectives.</p>
</section>
</section>
<section id="references" class="level1">
<h1><strong>References</strong></h1>
<ul>
<li>Singapore Department of Statistics (SingStat). <em>Monthly Retail Sales and Food &amp; Beverage Services Statistics, July 2025.</em> <a href="https://www.singstat.gov.sg/mrs?utm_source=chatgpt.com">https://www.singstat.gov.sg/mrs</a></li>
<li>Singapore Department of Statistics (SingStat). <em>Tourism Statistics – Industry &amp; Services.</em> <a href="https://www.singstat.gov.sg/find-data/search-by-theme/industry/tourism?utm_source=chatgpt.com">https://www.singstat.gov.sg/find-data/search-by-theme/industry/tourism</a></li>
<li>Singapore Tourism Board (STB). <em>Singapore achieves historical high in tourism receipts in 2024.</em> (Press Release, 29 January 2025). <a href="https://www.stb.gov.sg/about-stb/media-publications/media-centre/singapore-achieves-historical-high-in-tourism-receipts-in-2024/?utm_source=chatgpt.com">https://www.stb.gov.sg/about-stb/media-publications/media-centre/singapore-achieves-historical-high-in-tourism-receipts-in-2024/</a></li>
<li>Kam, T. S. (2024). <em>R for Geospatial Data Science and Analytics</em>. <a href="https://r4gdsa.netlify.app/" class="uri">https://r4gdsa.netlify.app/</a></li>
<li>Baddeley, A., Rubak, E., &amp; Turner, R. (2015). <em>Spatial Point Patterns: Methodology and Applications with R</em>. Chapman &amp; Hall/CRC.</li>
<li>Diggle, P. J. (2013). <em>Statistical Analysis of Spatial and Spatio-Temporal Point Patterns</em> (3rd ed.). CRC Press.</li>
</ul>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>